// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/istiqoma-landing/AppDemoCenter.tsx": () => import("../components/mockups/istiqoma-landing/AppDemoCenter.tsx"),
  "./components/mockups/istiqoma-landing/IslamicEditorial.tsx": () => import("../components/mockups/istiqoma-landing/IslamicEditorial.tsx"),
  "./components/mockups/istiqoma-landing/PromiseFirst.tsx": () => import("../components/mockups/istiqoma-landing/PromiseFirst.tsx"),
  "./components/mockups/istiqoma-landing/SocialProofLed.tsx": () => import("../components/mockups/istiqoma-landing/SocialProofLed.tsx")
};
