import { db } from "./db";
import { quizQuestions } from "@workspace/db";
import { sql, and, eq } from "drizzle-orm";

// ─── Authoring guide ────────────────────────────────────────────
// To add more questions:
//   1. Append entries to SEED_QUESTIONS below using the SeedQuestion shape.
//      • level         — integer, 1+. New levels above the current max are
//                        fine; the seeder fills any level that has zero rows.
//      • questionText  — the prompt the user sees (English, source of truth).
//      • options       — exactly 4 answer choices (tuple of 4 strings).
//      • correctIndex  — 0-based index of the correct option.
//      • explanation   — shown after the user answers; cite source if useful.
//      • category      — short tag (e.g. "Aqidah", "Salah", "Seerah").
//      • questionTextId / optionsId / explanationId  — Indonesian translations.
//      • questionTextMs / optionsMs / explanationMs  — Malay translations.
//        Arabic-derived Islamic terms (Salah, Wudu, Hajj, Sawm, ﷺ, (a.s.),
//        (r.a.), surah names, etc.) stay verbatim in all locales.
//   2. Boot the server. The seeder inserts questions only for levels that
//      currently have no rows in `quiz_questions`, so existing seeded
//      questions are preserved verbatim and re-seeding is safe.
//      Translations are upserted onto existing rows by (level, questionText).
//   3. To replace or edit a question that's already in the DB, edit it
//      directly (SQL/UI) — the seed file is append-only at runtime.
// ────────────────────────────────────────────────────────────────

type SeedQuestion = {
  level: number;
  questionText: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
  category: string;
  questionTextId?: string;
  optionsId?: [string, string, string, string];
  explanationId?: string;
  questionTextMs?: string;
  optionsMs?: [string, string, string, string];
  explanationMs?: string;
};

const SEED_QUESTIONS: SeedQuestion[] = [
  // ── Level 1 — Foundations of Faith ────────────────────────────
  {
    level: 1, category: "Aqidah",
    questionText: "How many pillars of Islam are there?",
    options: ["3", "4", "5", "6"], correctIndex: 2,
    explanation: "The five pillars are Shahadah, Salah, Zakah, Sawm (fasting Ramadan), and Hajj.",
    questionTextId: "Berapa jumlah rukun Islam?",
    optionsId: ["3", "4", "5", "6"],
    explanationId: "Lima rukun Islam adalah Shahadah, Salah, Zakah, Sawm (puasa Ramadan), dan Hajj.",
    questionTextMs: "Berapakah bilangan Rukun Islam?",
    optionsMs: ["3", "4", "5", "6"],
    explanationMs: "Lima Rukun Islam ialah Shahadah, Salah, Zakah, Sawm (puasa Ramadan), dan Hajj.",
  },
  {
    level: 1, category: "Aqidah",
    questionText: "Who is the final messenger of Allah?",
    options: ["Prophet Isa (a.s.)", "Prophet Musa (a.s.)", "Prophet Muhammad ﷺ", "Prophet Ibrahim (a.s.)"], correctIndex: 2,
    explanation: "Prophet Muhammad ﷺ is the seal of the prophets (Khatam an-Nabiyyin).",
    questionTextId: "Siapakah rasul terakhir Allah?",
    optionsId: ["Nabi Isa (a.s.)", "Nabi Musa (a.s.)", "Nabi Muhammad ﷺ", "Nabi Ibrahim (a.s.)"],
    explanationId: "Nabi Muhammad ﷺ adalah penutup para nabi (Khatam an-Nabiyyin).",
    questionTextMs: "Siapakah rasul terakhir Allah?",
    optionsMs: ["Nabi Isa (a.s.)", "Nabi Musa (a.s.)", "Nabi Muhammad ﷺ", "Nabi Ibrahim (a.s.)"],
    explanationMs: "Nabi Muhammad ﷺ adalah Khatam an-Nabiyyin (Penutup Para Nabi).",
  },
  {
    level: 1, category: "Salah",
    questionText: "How many obligatory daily prayers are there?",
    options: ["3", "4", "5", "6"], correctIndex: 2,
    explanation: "Fajr, Dhuhr, Asr, Maghrib, and Isha — five fardh prayers each day.",
    questionTextId: "Berapa jumlah sholat fardhu dalam sehari?",
    optionsId: ["3", "4", "5", "6"],
    explanationId: "Subuh, Zuhur, Asar, Maghrib, dan Isya — lima sholat fardhu setiap hari.",
    questionTextMs: "Berapakah bilangan solat fardhu sehari?",
    optionsMs: ["3", "4", "5", "6"],
    explanationMs: "Subuh, Zohor, Asar, Maghrib, dan Isyak — lima solat fardhu setiap hari.",
  },
  {
    level: 1, category: "Quran",
    questionText: "What is the first Surah of the Quran?",
    options: ["Al-Baqarah", "Al-Fatihah", "An-Nas", "Al-Ikhlas"], correctIndex: 1,
    explanation: "Al-Fatihah is the opening chapter and is recited in every rak'ah of salah.",
    questionTextId: "Apa Surah pertama dalam Al-Quran?",
    optionsId: ["Al-Baqarah", "Al-Fatihah", "An-Nas", "Al-Ikhlas"],
    explanationId: "Al-Fatihah adalah surah pembuka dan dibaca di setiap rakaat sholat.",
    questionTextMs: "Apakah Surah pertama dalam Al-Quran?",
    optionsMs: ["Al-Baqarah", "Al-Fatihah", "An-Nas", "Al-Ikhlas"],
    explanationMs: "Al-Fatihah ialah surah pembuka dan dibaca pada setiap rakaat solat.",
  },
  {
    level: 1, category: "Sawm",
    questionText: "In which month do Muslims fast from dawn to sunset?",
    options: ["Sha'ban", "Ramadan", "Muharram", "Rajab"], correctIndex: 1,
    explanation: "Fasting in Ramadan is the fourth pillar of Islam.",
    questionTextId: "Di bulan apa umat Islam berpuasa dari fajar hingga terbenamnya matahari?",
    optionsId: ["Sha'ban", "Ramadan", "Muharram", "Rajab"],
    explanationId: "Berpuasa di bulan Ramadan adalah rukun Islam keempat.",
    questionTextMs: "Pada bulan apakah umat Islam berpuasa dari fajar hingga matahari terbenam?",
    optionsMs: ["Sha'ban", "Ramadan", "Muharram", "Rajab"],
    explanationMs: "Berpuasa pada bulan Ramadan adalah rukun Islam yang keempat.",
  },
  {
    level: 1, category: "Aqidah",
    questionText: "What is the literal meaning of the word \"Islam\"?",
    options: ["Peace and submission", "Faith", "Worship", "Mercy"], correctIndex: 0,
    explanation: "Islam comes from the root s-l-m, meaning peace and submission to Allah's will.",
    questionTextId: "Apa arti harfiah kata \"Islam\"?",
    optionsId: ["Damai dan ketundukan", "Iman", "Ibadah", "Rahmat"],
    explanationId: "Islam berasal dari akar kata s-l-m, yang berarti damai dan tunduk kepada kehendak Allah.",
    questionTextMs: "Apakah maksud harfiah perkataan \"Islam\"?",
    optionsMs: ["Damai dan penyerahan diri", "Iman", "Ibadah", "Rahmat"],
    explanationMs: "Islam berasal dari akar kata s-l-m, bermaksud damai dan tunduk kepada kehendak Allah.",
  },
  {
    level: 1, category: "Aqidah",
    questionText: "How many angels are mentioned by name and role as required belief?",
    options: ["Belief in all of them", "Only Jibril", "Only the four archangels", "None"], correctIndex: 0,
    explanation: "Muslims must believe in all angels of Allah, even those whose names we do not know.",
    questionTextId: "Berapa malaikat yang wajib diketahui nama dan tugasnya?",
    optionsId: ["Percaya pada semua malaikat", "Hanya Jibril", "Hanya empat malaikat agung", "Tidak ada"],
    explanationId: "Muslim wajib percaya pada semua malaikat Allah, termasuk yang namanya tidak kita ketahui.",
    questionTextMs: "Berapakah malaikat yang wajib diketahui nama dan tugasnya?",
    optionsMs: ["Percaya pada semua malaikat", "Hanya Jibril", "Hanya empat malaikat agung", "Tiada"],
    explanationMs: "Muslim wajib percaya kepada semua malaikat Allah, termasuk yang namanya tidak kita ketahui.",
  },
  {
    level: 1, category: "Hajj",
    questionText: "Which holy city must every able Muslim visit at least once for Hajj?",
    options: ["Madinah", "Jerusalem", "Makkah", "Cairo"], correctIndex: 2,
    explanation: "Hajj is performed at the Ka'bah in Makkah.",
    questionTextId: "Kota suci mana yang wajib dikunjungi setiap Muslim yang mampu untuk Hajj?",
    optionsId: ["Madinah", "Yerusalem", "Makkah", "Kairo"],
    explanationId: "Hajj dilaksanakan di Ka'bah di Makkah.",
    questionTextMs: "Bandar suci manakah yang wajib dikunjungi oleh setiap Muslim yang mampu untuk Hajj?",
    optionsMs: ["Madinah", "Jerusalem", "Makkah", "Kaherah"],
    explanationMs: "Hajj dilaksanakan di Ka'bah di Makkah.",
  },
  {
    level: 1, category: "Quran",
    questionText: "In which language was the Quran originally revealed?",
    options: ["Hebrew", "Aramaic", "Arabic", "Persian"], correctIndex: 2,
    explanation: "The Quran was revealed in Arabic, as Allah states in Surah Yusuf 12:2.",
    questionTextId: "Dalam bahasa apa Al-Quran pertama kali diturunkan?",
    optionsId: ["Ibrani", "Aram", "Arab", "Persia"],
    explanationId: "Al-Quran diturunkan dalam bahasa Arab, sebagaimana dinyatakan Allah dalam Surah Yusuf 12:2.",
    questionTextMs: "Dalam bahasa apakah Al-Quran pada asalnya diturunkan?",
    optionsMs: ["Ibrani", "Aram", "Arab", "Parsi"],
    explanationMs: "Al-Quran diturunkan dalam bahasa Arab, sebagaimana yang dinyatakan Allah dalam Surah Yusuf 12:2.",
  },
  {
    level: 1, category: "Aqidah",
    questionText: "What is the Shahadah?",
    options: ["The pilgrimage", "The fast", "The testimony of faith", "The charity"], correctIndex: 2,
    explanation: "The Shahadah is bearing witness that there is no god but Allah and Muhammad ﷺ is His messenger.",
    questionTextId: "Apa itu Shahadah?",
    optionsId: ["Ibadah haji", "Puasa", "Kesaksian iman", "Zakat"],
    explanationId: "Shahadah adalah bersaksi bahwa tidak ada tuhan selain Allah dan Muhammad ﷺ adalah utusan-Nya.",
    questionTextMs: "Apakah itu Shahadah?",
    optionsMs: ["Menunaikan haji", "Berpuasa", "Ikrar keimanan", "Zakat"],
    explanationMs: "Shahadah ialah bersaksi bahawa tiada tuhan selain Allah dan Muhammad ﷺ adalah utusan-Nya.",
  },

  // ── Level 2 — Salah & Worship ────────────────────────────────
  {
    level: 2, category: "Salah",
    questionText: "How many rak'ahs are in Fajr (fardh)?",
    options: ["2", "3", "4", "5"], correctIndex: 0,
    explanation: "Fajr fardh is two rak'ahs, preceded by two sunnah rak'ahs.",
    questionTextId: "Berapa rakaat dalam sholat Subuh (fardhu)?",
    optionsId: ["2", "3", "4", "5"],
    explanationId: "Subuh fardhu adalah dua rakaat, didahului dua rakaat sunnah.",
    questionTextMs: "Berapakah rakaat dalam solat Subuh (fardhu)?",
    optionsMs: ["2", "3", "4", "5"],
    explanationMs: "Solat Subuh fardhu adalah dua rakaat, didahului dua rakaat sunat.",
  },
  {
    level: 2, category: "Salah",
    questionText: "How many rak'ahs are in Maghrib (fardh)?",
    options: ["2", "3", "4", "5"], correctIndex: 1,
    explanation: "Maghrib fardh is three rak'ahs.",
    questionTextId: "Berapa rakaat dalam sholat Maghrib (fardhu)?",
    optionsId: ["2", "3", "4", "5"],
    explanationId: "Maghrib fardhu adalah tiga rakaat.",
    questionTextMs: "Berapakah rakaat dalam solat Maghrib (fardhu)?",
    optionsMs: ["2", "3", "4", "5"],
    explanationMs: "Solat Maghrib fardhu adalah tiga rakaat.",
  },
  {
    level: 2, category: "Salah",
    questionText: "What direction do Muslims face in prayer?",
    options: ["East", "Towards Makkah (Qiblah)", "North", "Towards Madinah"], correctIndex: 1,
    explanation: "Muslims face the Qiblah — the direction of the Ka'bah in Makkah.",
    questionTextId: "Ke arah mana umat Islam menghadap saat sholat?",
    optionsId: ["Timur", "Ke arah Makkah (Qiblah)", "Utara", "Ke arah Madinah"],
    explanationId: "Muslim menghadap Qiblah — arah Ka'bah di Makkah.",
    questionTextMs: "Ke arah manakah umat Islam menghadap semasa solat?",
    optionsMs: ["Timur", "Ke arah Makkah (Qiblah)", "Utara", "Ke arah Madinah"],
    explanationMs: "Muslim menghadap Qiblah — arah Ka'bah di Makkah.",
  },
  {
    level: 2, category: "Wudu",
    questionText: "Which act invalidates wudu?",
    options: ["Drinking water", "Speaking", "Passing wind", "Looking at the Quran"], correctIndex: 2,
    explanation: "Passing wind, urinating, defecating, and deep sleep break wudu.",
    questionTextId: "Perbuatan apa yang membatalkan wudhu?",
    optionsId: ["Minum air", "Berbicara", "Kentut", "Melihat Al-Quran"],
    explanationId: "Kentut, buang air kecil, buang air besar, dan tidur lelap membatalkan wudhu.",
    questionTextMs: "Perbuatan apakah yang membatalkan Wudu?",
    optionsMs: ["Minum air", "Bercakap", "Kentut", "Melihat Al-Quran"],
    explanationMs: "Kentut, kencing, buang air besar, dan tidur nyenyak membatalkan Wudu.",
  },
  {
    level: 2, category: "Salah",
    questionText: "Which Surah is recited in every rak'ah of salah?",
    options: ["Al-Ikhlas", "Al-Fatihah", "Al-Falaq", "An-Nas"], correctIndex: 1,
    explanation: "Al-Fatihah is recited in every rak'ah; the Prophet ﷺ said no prayer is valid without it.",
    questionTextId: "Surah apa yang dibaca di setiap rakaat sholat?",
    optionsId: ["Al-Ikhlas", "Al-Fatihah", "Al-Falaq", "An-Nas"],
    explanationId: "Al-Fatihah dibaca di setiap rakaat; Nabi ﷺ bersabda tidak sah sholat tanpa membacanya.",
    questionTextMs: "Surah apakah yang dibaca pada setiap rakaat solat?",
    optionsMs: ["Al-Ikhlas", "Al-Fatihah", "Al-Falaq", "An-Nas"],
    explanationMs: "Al-Fatihah dibaca pada setiap rakaat; Nabi ﷺ bersabda solat tidak sah tanpanya.",
  },
  {
    level: 2, category: "Salah",
    questionText: "What is the night prayer voluntarily performed in Ramadan called?",
    options: ["Tahajjud", "Witr", "Tarawih", "Duha"], correctIndex: 2,
    explanation: "Tarawih is the special night prayer of Ramadan, prayed in congregation after Isha.",
    questionTextId: "Apa nama sholat malam yang dilakukan secara sunnah di bulan Ramadan?",
    optionsId: ["Tahajjud", "Witir", "Tarawih", "Dhuha"],
    explanationId: "Tarawih adalah sholat malam khusus Ramadan, dikerjakan berjamaah setelah Isya.",
    questionTextMs: "Apakah nama solat malam yang dilakukan secara sunat pada bulan Ramadan?",
    optionsMs: ["Tahajjud", "Witir", "Tarawih", "Dhuha"],
    explanationMs: "Tarawih adalah solat malam khusus Ramadan, dilaksanakan berjemaah selepas Isyak.",
  },
  {
    level: 2, category: "Wudu",
    questionText: "How many times is each washed limb typically rinsed in wudu (sunnah)?",
    options: ["Once", "Twice", "Three times", "Five times"], correctIndex: 2,
    explanation: "Three times is the sunnah, though once is the obligatory minimum for most limbs.",
    questionTextId: "Berapa kali setiap anggota wudhu biasanya dibasuh (sunnah)?",
    optionsId: ["Sekali", "Dua kali", "Tiga kali", "Lima kali"],
    explanationId: "Tiga kali adalah sunnah, meskipun sekali adalah minimum wajib untuk sebagian besar anggota.",
    questionTextMs: "Berapakah kali setiap anggota Wudu biasanya dibasuh (sunat)?",
    optionsMs: ["Sekali", "Dua kali", "Tiga kali", "Lima kali"],
    explanationMs: "Tiga kali adalah sunat, walaupun sekali adalah minimum wajib bagi kebanyakan anggota.",
  },
  {
    level: 2, category: "Salah",
    questionText: "What is the call to prayer called?",
    options: ["Iqamah", "Adhan", "Khutbah", "Dua"], correctIndex: 1,
    explanation: "The Adhan is the public call announcing prayer time; the Iqamah is the second call right before salah begins.",
    questionTextId: "Apa nama panggilan untuk sholat?",
    optionsId: ["Iqamah", "Adzan", "Khutbah", "Doa"],
    explanationId: "Adzan adalah seruan umum yang mengumumkan waktu sholat; Iqamah adalah seruan kedua tepat sebelum sholat dimulai.",
    questionTextMs: "Apakah nama seruan untuk solat?",
    optionsMs: ["Iqamah", "Azan", "Khutbah", "Doa"],
    explanationMs: "Azan adalah seruan awam yang mengumumkan waktu solat; Iqamah adalah seruan kedua sebelum solat dimulakan.",
  },
  {
    level: 2, category: "Salah",
    questionText: "Friday congregational prayer is known as:",
    options: ["Salah al-Eid", "Salah al-Jumu'ah", "Salah al-Janazah", "Salah al-Istikharah"], correctIndex: 1,
    explanation: "Salah al-Jumu'ah replaces Dhuhr on Fridays and includes a khutbah (sermon).",
    questionTextId: "Sholat berjamaah hari Jumat dikenal sebagai:",
    optionsId: ["Salah al-Eid", "Salah al-Jumu'ah", "Salah al-Janazah", "Salah al-Istikharah"],
    explanationId: "Salah al-Jumu'ah menggantikan Zuhur pada hari Jumat dan mencakup khutbah (ceramah).",
    questionTextMs: "Solat berjemaah hari Jumaat dikenali sebagai:",
    optionsMs: ["Salah al-Eid", "Salah al-Jumu'ah", "Salah al-Janazah", "Salah al-Istikharah"],
    explanationMs: "Salah al-Jumu'ah menggantikan Zohor pada hari Jumaat dan termasuk khutbah (ceramah).",
  },
  {
    level: 2, category: "Salah",
    questionText: "What position is described by the word \"sujood\"?",
    options: ["Standing", "Bowing", "Prostration", "Sitting"], correctIndex: 2,
    explanation: "Sujood is the prostration with forehead, nose, palms, knees, and toes touching the ground.",
    questionTextId: "Posisi apa yang digambarkan dengan kata \"sujood\"?",
    optionsId: ["Berdiri", "Rukuk", "Sujud", "Duduk"],
    explanationId: "Sujud adalah posisi sujud dengan dahi, hidung, telapak tangan, lutut, dan jari kaki menyentuh lantai.",
    questionTextMs: "Apakah posisi yang digambarkan oleh perkataan \"sujood\"?",
    optionsMs: ["Berdiri", "Rukuk", "Sujud", "Duduk"],
    explanationMs: "Sujud adalah posisi sujud dengan dahi, hidung, tapak tangan, lutut, dan jari kaki menyentuh lantai.",
  },

  // ── Level 3 — Quran & Prophets ───────────────────────────────
  {
    level: 3, category: "Quran",
    questionText: "How many Surahs are in the Quran?",
    options: ["99", "114", "120", "100"], correctIndex: 1,
    explanation: "The Quran contains 114 Surahs (chapters).",
    questionTextId: "Berapa jumlah Surah dalam Al-Quran?",
    optionsId: ["99", "114", "120", "100"],
    explanationId: "Al-Quran terdiri dari 114 Surah (bab).",
    questionTextMs: "Berapakah bilangan Surah dalam Al-Quran?",
    optionsMs: ["99", "114", "120", "100"],
    explanationMs: "Al-Quran mengandungi 114 Surah (bab).",
  },
  {
    level: 3, category: "Quran",
    questionText: "Which is the longest Surah of the Quran?",
    options: ["Al-Baqarah", "Yasin", "Al-Kahf", "Al-Imran"], correctIndex: 0,
    explanation: "Surah Al-Baqarah, with 286 verses, is the longest chapter.",
    questionTextId: "Surah apa yang paling panjang dalam Al-Quran?",
    optionsId: ["Al-Baqarah", "Yasin", "Al-Kahf", "Al-Imran"],
    explanationId: "Surah Al-Baqarah, dengan 286 ayat, adalah bab terpanjang.",
    questionTextMs: "Surah manakah yang paling panjang dalam Al-Quran?",
    optionsMs: ["Al-Baqarah", "Yasin", "Al-Kahf", "Al-Imran"],
    explanationMs: "Surah Al-Baqarah, dengan 286 ayat, adalah bab yang paling panjang.",
  },
  {
    level: 3, category: "Quran",
    questionText: "Which Surah is known as the \"heart of the Quran\"?",
    options: ["Al-Fatihah", "Yasin", "Al-Mulk", "Al-Rahman"], correctIndex: 1,
    explanation: "The Prophet ﷺ called Surah Yasin the heart of the Quran in a well-known narration.",
    questionTextId: "Surah apa yang dikenal sebagai \"jantung Al-Quran\"?",
    optionsId: ["Al-Fatihah", "Yasin", "Al-Mulk", "Al-Rahman"],
    explanationId: "Nabi ﷺ menyebut Surah Yasin sebagai jantung Al-Quran dalam sebuah riwayat yang terkenal.",
    questionTextMs: "Surah apakah yang dikenali sebagai \"jantung Al-Quran\"?",
    optionsMs: ["Al-Fatihah", "Yasin", "Al-Mulk", "Al-Rahman"],
    explanationMs: "Nabi ﷺ menyebut Surah Yasin sebagai jantung Al-Quran dalam sebuah riwayat yang terkenal.",
  },
  {
    level: 3, category: "Prophets",
    questionText: "Which prophet is known as Khalilullah (the friend of Allah)?",
    options: ["Musa (a.s.)", "Ibrahim (a.s.)", "Isa (a.s.)", "Nuh (a.s.)"], correctIndex: 1,
    explanation: "Allah took Ibrahim (a.s.) as a Khalil — a close friend (Quran 4:125).",
    questionTextId: "Nabi mana yang dikenal sebagai Khalilullah (kekasih Allah)?",
    optionsId: ["Musa (a.s.)", "Ibrahim (a.s.)", "Isa (a.s.)", "Nuh (a.s.)"],
    explanationId: "Allah menjadikan Ibrahim (a.s.) sebagai Khalil — sahabat dekat (Quran 4:125).",
    questionTextMs: "Nabi manakah yang dikenali sebagai Khalilullah (kekasih Allah)?",
    optionsMs: ["Musa (a.s.)", "Ibrahim (a.s.)", "Isa (a.s.)", "Nuh (a.s.)"],
    explanationMs: "Allah menjadikan Ibrahim (a.s.) sebagai Khalil — kekasih yang hampir (Quran 4:125).",
  },
  {
    level: 3, category: "Prophets",
    questionText: "Which prophet was given the Torah?",
    options: ["Isa (a.s.)", "Dawud (a.s.)", "Musa (a.s.)", "Ibrahim (a.s.)"], correctIndex: 2,
    explanation: "Musa (a.s.) received the Tawrat (Torah) on Mount Sinai.",
    questionTextId: "Nabi mana yang diberikan Kitab Taurat?",
    optionsId: ["Isa (a.s.)", "Dawud (a.s.)", "Musa (a.s.)", "Ibrahim (a.s.)"],
    explanationId: "Musa (a.s.) menerima Tawrat (Taurat) di Gunung Sinai.",
    questionTextMs: "Nabi manakah yang diturunkan Kitab Taurat?",
    optionsMs: ["Isa (a.s.)", "Dawud (a.s.)", "Musa (a.s.)", "Ibrahim (a.s.)"],
    explanationMs: "Musa (a.s.) menerima Tawrat (Taurat) di Bukit Sinai.",
  },
  {
    level: 3, category: "Prophets",
    questionText: "Which prophet was given the Zabur (Psalms)?",
    options: ["Sulayman (a.s.)", "Dawud (a.s.)", "Yahya (a.s.)", "Ya'qub (a.s.)"], correctIndex: 1,
    explanation: "Dawud (a.s.) was given the Zabur (Quran 4:163).",
    questionTextId: "Nabi mana yang diberikan Kitab Zabur?",
    optionsId: ["Sulayman (a.s.)", "Dawud (a.s.)", "Yahya (a.s.)", "Ya'qub (a.s.)"],
    explanationId: "Dawud (a.s.) diberikan Zabur (Quran 4:163).",
    questionTextMs: "Nabi manakah yang diturunkan Kitab Zabur?",
    optionsMs: ["Sulayman (a.s.)", "Dawud (a.s.)", "Yahya (a.s.)", "Ya'qub (a.s.)"],
    explanationMs: "Dawud (a.s.) diturunkan Zabur (Quran 4:163).",
  },
  {
    level: 3, category: "Quran",
    questionText: "How many years did the revelation of the Quran take?",
    options: ["10 years", "Approximately 23 years", "30 years", "5 years"], correctIndex: 1,
    explanation: "Revelation began at age 40 and continued until the Prophet's ﷺ death — about 23 years.",
    questionTextId: "Berapa tahun proses turunnya Al-Quran?",
    optionsId: ["10 tahun", "Sekitar 23 tahun", "30 tahun", "5 tahun"],
    explanationId: "Wahyu dimulai pada usia 40 tahun dan berlangsung hingga wafatnya Nabi ﷺ — sekitar 23 tahun.",
    questionTextMs: "Berapa tahunkah proses penurunan Al-Quran?",
    optionsMs: ["10 tahun", "Lebih kurang 23 tahun", "30 tahun", "5 tahun"],
    explanationMs: "Wahyu bermula pada usia 40 tahun dan berterusan sehingga kewafatan Nabi ﷺ — lebih kurang 23 tahun.",
  },
  {
    level: 3, category: "Quran",
    questionText: "What is the night the Quran was first revealed called?",
    options: ["Laylat al-Bara'ah", "Laylat al-Qadr", "Laylat al-Mi'raj", "Laylat al-Isra"], correctIndex: 1,
    explanation: "Laylat al-Qadr — the Night of Power — is described in Surah Al-Qadr.",
    questionTextId: "Apa nama malam pertama Al-Quran diturunkan?",
    optionsId: ["Laylat al-Bara'ah", "Laylat al-Qadr", "Laylat al-Mi'raj", "Laylat al-Isra"],
    explanationId: "Laylat al-Qadr — Malam Kemuliaan — digambarkan dalam Surah Al-Qadr.",
    questionTextMs: "Apakah nama malam pertama Al-Quran diturunkan?",
    optionsMs: ["Laylat al-Bara'ah", "Laylat al-Qadr", "Laylat al-Mi'raj", "Laylat al-Isra"],
    explanationMs: "Laylat al-Qadr — Malam Kemuliaan — digambarkan dalam Surah Al-Qadr.",
  },
  {
    level: 3, category: "Quran",
    questionText: "How many ajza (parts/juz) is the Quran divided into?",
    options: ["20", "30", "40", "60"], correctIndex: 1,
    explanation: "The Quran is divided into 30 juz to facilitate recitation, especially in Ramadan.",
    questionTextId: "Al-Quran dibagi menjadi berapa juz?",
    optionsId: ["20", "30", "40", "60"],
    explanationId: "Al-Quran dibagi menjadi 30 juz untuk memudahkan pembacaan, terutama di bulan Ramadan.",
    questionTextMs: "Al-Quran dibahagikan kepada berapa juz?",
    optionsMs: ["20", "30", "40", "60"],
    explanationMs: "Al-Quran dibahagikan kepada 30 juz untuk memudahkan bacaan, terutama pada bulan Ramadan.",
  },
  {
    level: 3, category: "Prophets",
    questionText: "Which prophet's people were destroyed by a great flood?",
    options: ["Hud (a.s.)", "Salih (a.s.)", "Nuh (a.s.)", "Lut (a.s.)"], correctIndex: 2,
    explanation: "The flood was sent in the time of Nuh (a.s.) for those who rejected his message.",
    questionTextId: "Umat nabi mana yang dihancurkan oleh banjir besar?",
    optionsId: ["Hud (a.s.)", "Salih (a.s.)", "Nuh (a.s.)", "Lut (a.s.)"],
    explanationId: "Banjir dikirimkan pada zaman Nuh (a.s.) bagi mereka yang menolak ajarannya.",
    questionTextMs: "Umat nabi manakah yang dimusnahkan oleh banjir besar?",
    optionsMs: ["Hud (a.s.)", "Salih (a.s.)", "Nuh (a.s.)", "Lut (a.s.)"],
    explanationMs: "Banjir dihantar pada zaman Nuh (a.s.) bagi mereka yang menolak ajarannya.",
  },

  // ── Level 4 — Seerah & History ───────────────────────────────
  {
    level: 4, category: "Seerah",
    questionText: "In which city was Prophet Muhammad ﷺ born?",
    options: ["Madinah", "Makkah", "Ta'if", "Khaybar"], correctIndex: 1,
    explanation: "He ﷺ was born in Makkah in the Year of the Elephant (~570 CE).",
    questionTextId: "Di kota mana Nabi Muhammad ﷺ dilahirkan?",
    optionsId: ["Madinah", "Makkah", "Ta'if", "Khaybar"],
    explanationId: "Beliau ﷺ dilahirkan di Makkah pada Tahun Gajah (~570 M).",
    questionTextMs: "Di bandar manakah Nabi Muhammad ﷺ dilahirkan?",
    optionsMs: ["Madinah", "Makkah", "Ta'if", "Khaybar"],
    explanationMs: "Baginda ﷺ dilahirkan di Makkah pada Tahun Gajah (~570 M).",
  },
  {
    level: 4, category: "Seerah",
    questionText: "Who was the Prophet ﷺ's first wife?",
    options: ["Aisha (r.a.)", "Hafsa (r.a.)", "Khadijah (r.a.)", "Sawda (r.a.)"], correctIndex: 2,
    explanation: "Khadijah bint Khuwaylid (r.a.) was his first wife and the first to believe in him.",
    questionTextId: "Siapakah istri pertama Nabi ﷺ?",
    optionsId: ["Aisha (r.a.)", "Hafsa (r.a.)", "Khadijah (r.a.)", "Sawda (r.a.)"],
    explanationId: "Khadijah binti Khuwaylid (r.a.) adalah istri pertama beliau dan orang pertama yang beriman kepadanya.",
    questionTextMs: "Siapakah isteri pertama Nabi ﷺ?",
    optionsMs: ["Aisha (r.a.)", "Hafsa (r.a.)", "Khadijah (r.a.)", "Sawda (r.a.)"],
    explanationMs: "Khadijah binti Khuwaylid (r.a.) adalah isteri pertama baginda dan orang pertama yang beriman kepadanya.",
  },
  {
    level: 4, category: "Seerah",
    questionText: "What is the migration from Makkah to Madinah called?",
    options: ["Isra", "Mi'raj", "Hijrah", "Fath"], correctIndex: 2,
    explanation: "The Hijrah marks the start of the Islamic (Hijri) calendar.",
    questionTextId: "Apa nama perpindahan dari Makkah ke Madinah?",
    optionsId: ["Isra", "Mi'raj", "Hijrah", "Fath"],
    explanationId: "Hijrah menandai awal kalender Islam (Hijriah).",
    questionTextMs: "Apakah nama penghijrahan dari Makkah ke Madinah?",
    optionsMs: ["Isra", "Mi'raj", "Hijrah", "Fath"],
    explanationMs: "Hijrah menandakan permulaan kalendar Islam (Hijriah).",
  },
  {
    level: 4, category: "Seerah",
    questionText: "Who was the first caliph after the Prophet ﷺ?",
    options: ["Umar ibn al-Khattab (r.a.)", "Uthman ibn Affan (r.a.)", "Ali ibn Abi Talib (r.a.)", "Abu Bakr as-Siddiq (r.a.)"], correctIndex: 3,
    explanation: "Abu Bakr as-Siddiq (r.a.) was chosen as the first Khalifah.",
    questionTextId: "Siapakah khalifah pertama setelah Nabi ﷺ?",
    optionsId: ["Umar ibn al-Khattab (r.a.)", "Uthman ibn Affan (r.a.)", "Ali ibn Abi Talib (r.a.)", "Abu Bakr as-Siddiq (r.a.)"],
    explanationId: "Abu Bakr as-Siddiq (r.a.) dipilih sebagai Khalifah pertama.",
    questionTextMs: "Siapakah khalifah pertama selepas Nabi ﷺ?",
    optionsMs: ["Umar ibn al-Khattab (r.a.)", "Uthman ibn Affan (r.a.)", "Ali ibn Abi Talib (r.a.)", "Abu Bakr as-Siddiq (r.a.)"],
    explanationMs: "Abu Bakr as-Siddiq (r.a.) dipilih sebagai Khalifah pertama.",
  },
  {
    level: 4, category: "Seerah",
    questionText: "Which battle is known as the first major battle in Islam?",
    options: ["Uhud", "Khandaq", "Badr", "Hunayn"], correctIndex: 2,
    explanation: "The Battle of Badr (2 AH) was the first decisive battle, with the Muslims outnumbered roughly 3:1.",
    questionTextId: "Perang apa yang dikenal sebagai perang besar pertama dalam Islam?",
    optionsId: ["Uhud", "Khandaq", "Badr", "Hunayn"],
    explanationId: "Perang Badr (2 H) adalah pertempuran menentukan pertama, dengan kaum Muslim kalah jumlah sekitar 3:1.",
    questionTextMs: "Perang apakah yang dikenali sebagai perang besar pertama dalam Islam?",
    optionsMs: ["Uhud", "Khandaq", "Badr", "Hunayn"],
    explanationMs: "Perang Badr (2H) adalah pertempuran menentukan pertama, dengan umat Islam kalah jumlah kira-kira 3:1.",
  },
  {
    level: 4, category: "Seerah",
    questionText: "Who was the Prophet ﷺ's youngest daughter?",
    options: ["Zaynab", "Ruqayyah", "Umm Kulthum", "Fatimah"], correctIndex: 3,
    explanation: "Fatimah az-Zahra (r.a.) was his youngest daughter and the only one to outlive him briefly.",
    questionTextId: "Siapakah putri bungsu Nabi ﷺ?",
    optionsId: ["Zaynab", "Ruqayyah", "Umm Kulthum", "Fatimah"],
    explanationId: "Fatimah az-Zahra (r.a.) adalah putri bungsunya dan satu-satunya yang bertahan lebih lama darinya.",
    questionTextMs: "Siapakah puteri bongsu Nabi ﷺ?",
    optionsMs: ["Zaynab", "Ruqayyah", "Umm Kulthum", "Fatimah"],
    explanationMs: "Fatimah az-Zahra (r.a.) adalah puteri bongsu baginda dan satu-satunya yang masih hidup selepas kewafatan baginda.",
  },
  {
    level: 4, category: "Seerah",
    questionText: "At what age did Prophet Muhammad ﷺ receive the first revelation?",
    options: ["25", "30", "40", "50"], correctIndex: 2,
    explanation: "He ﷺ received the first revelation at age 40 in the Cave of Hira.",
    questionTextId: "Pada usia berapa Nabi Muhammad ﷺ menerima wahyu pertama?",
    optionsId: ["25", "30", "40", "50"],
    explanationId: "Beliau ﷺ menerima wahyu pertama pada usia 40 tahun di Gua Hira.",
    questionTextMs: "Pada usia berapakah Nabi Muhammad ﷺ menerima wahyu pertama?",
    optionsMs: ["25", "30", "40", "50"],
    explanationMs: "Baginda ﷺ menerima wahyu pertama pada usia 40 tahun di Gua Hira.",
  },
  {
    level: 4, category: "Seerah",
    questionText: "Which angel brought revelation to the Prophet ﷺ?",
    options: ["Mika'il", "Israfil", "Jibril", "Malik"], correctIndex: 2,
    explanation: "The angel Jibril (Gabriel) is the angel of revelation.",
    questionTextId: "Malaikat apa yang membawa wahyu kepada Nabi ﷺ?",
    optionsId: ["Mika'il", "Israfil", "Jibril", "Malik"],
    explanationId: "Malaikat Jibril adalah malaikat wahyu.",
    questionTextMs: "Malaikat manakah yang membawa wahyu kepada Nabi ﷺ?",
    optionsMs: ["Mika'il", "Israfil", "Jibril", "Malik"],
    explanationMs: "Malaikat Jibril adalah malaikat wahyu.",
  },
  {
    level: 4, category: "Seerah",
    questionText: "What is the night journey of the Prophet ﷺ from Makkah to Jerusalem called?",
    options: ["Hijrah", "Mi'raj", "Isra", "Fath"], correctIndex: 2,
    explanation: "Al-Isra is the night journey to Al-Aqsa; Al-Mi'raj is the ascension to the heavens that followed.",
    questionTextId: "Apa nama perjalanan malam Nabi ﷺ dari Makkah ke Yerusalem?",
    optionsId: ["Hijrah", "Mi'raj", "Isra", "Fath"],
    explanationId: "Al-Isra adalah perjalanan malam ke Al-Aqsa; Al-Mi'raj adalah kenaikan ke langit yang mengikutinya.",
    questionTextMs: "Apakah nama perjalanan malam Nabi ﷺ dari Makkah ke Baitulmaqdis?",
    optionsMs: ["Hijrah", "Mi'raj", "Isra", "Fath"],
    explanationMs: "Al-Isra adalah perjalanan malam ke Al-Aqsa; Al-Mi'raj adalah kenaikan ke langit yang berikutnya.",
  },
  {
    level: 4, category: "Seerah",
    questionText: "Which companion is known as \"the sword of Allah\"?",
    options: ["Khalid ibn al-Walid (r.a.)", "Sa'd ibn Abi Waqqas (r.a.)", "Abu Ubaydah (r.a.)", "Talha (r.a.)"], correctIndex: 0,
    explanation: "The Prophet ﷺ titled Khalid ibn al-Walid (r.a.) Sayfullah — the Sword of Allah.",
    questionTextId: "Sahabat mana yang dikenal sebagai \"pedang Allah\"?",
    optionsId: ["Khalid ibn al-Walid (r.a.)", "Sa'd ibn Abi Waqqas (r.a.)", "Abu Ubaydah (r.a.)", "Talha (r.a.)"],
    explanationId: "Nabi ﷺ memanggil Khalid ibn al-Walid (r.a.) Sayfullah — Pedang Allah.",
    questionTextMs: "Sahabat manakah yang dikenali sebagai \"pedang Allah\"?",
    optionsMs: ["Khalid ibn al-Walid (r.a.)", "Sa'd ibn Abi Waqqas (r.a.)", "Abu Ubaydah (r.a.)", "Talha (r.a.)"],
    explanationMs: "Nabi ﷺ menggelar Khalid ibn al-Walid (r.a.) Sayfullah — Pedang Allah.",
  },

  // ── Level 5 — Fiqh & Daily Practice ──────────────────────────
  {
    level: 5, category: "Zakah",
    questionText: "Zakah is generally what percentage of qualifying wealth held for a year?",
    options: ["1%", "2.5%", "5%", "10%"], correctIndex: 1,
    explanation: "Zakah on monetary wealth above the nisab is 2.5% per lunar year.",
    questionTextId: "Zakah umumnya berapa persen dari harta yang memenuhi syarat yang disimpan selama setahun?",
    optionsId: ["1%", "2,5%", "5%", "10%"],
    explanationId: "Zakah atas harta uang di atas nisab adalah 2,5% per tahun lunar.",
    questionTextMs: "Zakah umumnya berapa peratus daripada harta yang layak yang disimpan selama setahun?",
    optionsMs: ["1%", "2.5%", "5%", "10%"],
    explanationMs: "Zakah ke atas harta wang di atas nisab adalah 2.5% setahun lunar.",
  },
  {
    level: 5, category: "Sawm",
    questionText: "Which act invalidates the fast?",
    options: ["Brushing teeth", "Smelling food", "Eating intentionally", "Taking a shower"], correctIndex: 2,
    explanation: "Intentional eating, drinking, or sexual relations during fasting hours invalidate the fast.",
    questionTextId: "Perbuatan apa yang membatalkan puasa?",
    optionsId: ["Gosok gigi", "Mencium makanan", "Makan dengan sengaja", "Mandi"],
    explanationId: "Makan, minum, atau hubungan seksual dengan sengaja selama waktu puasa membatalkan puasa.",
    questionTextMs: "Perbuatan apakah yang membatalkan puasa?",
    optionsMs: ["Gosok gigi", "Menghidu makanan", "Makan dengan sengaja", "Mandi"],
    explanationMs: "Makan, minum, atau hubungan seksual dengan sengaja semasa waktu puasa membatalkan puasa.",
  },
  {
    level: 5, category: "Hajj",
    questionText: "Which act is the central pillar of Hajj?",
    options: ["Sa'i between Safa and Marwah", "Standing at Arafah", "Tawaf al-Wada", "Stoning the Jamarat"], correctIndex: 1,
    explanation: "The Prophet ﷺ said \"Hajj is Arafah\" — standing at Arafah on the 9th of Dhul-Hijjah is the essential pillar.",
    questionTextId: "Perbuatan apa yang merupakan rukun utama Hajj?",
    optionsId: ["Sa'i antara Safa dan Marwah", "Wukuf di Arafah", "Tawaf al-Wada", "Melempar Jumarat"],
    explanationId: "Nabi ﷺ bersabda \"Hajj adalah Arafah\" — wukuf di Arafah pada 9 Dzulhijjah adalah rukun yang wajib.",
    questionTextMs: "Perbuatan apakah yang merupakan rukun utama Hajj?",
    optionsMs: ["Sa'i antara Safa dan Marwah", "Wukuf di Arafah", "Tawaf al-Wada", "Melontar Jamarat"],
    explanationMs: "Nabi ﷺ bersabda \"Hajj adalah Arafah\" — wukuf di Arafah pada 9 Zulhijjah adalah rukun yang wajib.",
  },
  {
    level: 5, category: "Halal",
    questionText: "Which of these is haram to consume?",
    options: ["Beef slaughtered Islamically", "Pork", "Lamb", "Chicken slaughtered Islamically"], correctIndex: 1,
    explanation: "Pork, blood, carrion, and intoxicants are explicitly forbidden (Quran 5:3).",
    questionTextId: "Mana dari berikut ini yang haram untuk dikonsumsi?",
    optionsId: ["Daging sapi yang disembelih secara Islami", "Babi", "Kambing", "Ayam yang disembelih secara Islami"],
    explanationId: "Babi, darah, bangkai, dan minuman memabukkan secara tegas dilarang (Quran 5:3).",
    questionTextMs: "Manakah antara berikut yang haram untuk dimakan?",
    optionsMs: ["Daging lembu yang disembelih secara Islam", "Babi", "Kambing biri-biri", "Ayam yang disembelih secara Islam"],
    explanationMs: "Babi, darah, bangkai, dan minuman memabukkan diharamkan secara jelas (Quran 5:3).",
  },
  {
    level: 5, category: "Sawm",
    questionText: "What is the pre-dawn meal before fasting called?",
    options: ["Iftar", "Suhoor", "Tarawih", "I'tikaf"], correctIndex: 1,
    explanation: "Suhoor is the meal taken before Fajr; iftar is the meal that breaks the fast at sunset.",
    questionTextId: "Apa nama makan sebelum subuh sebelum berpuasa?",
    optionsId: ["Iftar", "Suhoor", "Tarawih", "I'tikaf"],
    explanationId: "Suhoor adalah makanan yang dimakan sebelum Subuh; iftar adalah makanan yang berbuka puasa saat terbenamnya matahari.",
    questionTextMs: "Apakah nama makan sahur sebelum berpuasa?",
    optionsMs: ["Iftar", "Suhoor", "Tarawih", "I'tikaf"],
    explanationMs: "Suhoor adalah makanan yang dimakan sebelum Subuh; iftar adalah makanan berbuka puasa ketika matahari terbenam.",
  },
  {
    level: 5, category: "Adab",
    questionText: "What should a Muslim say upon entering a home?",
    options: ["Bismillah", "Assalamu alaikum", "Alhamdulillah", "Masha'Allah"], correctIndex: 1,
    explanation: "The greeting of peace — \"Assalamu alaikum\" — is the sunnah upon entering, even an empty home (Quran 24:61).",
    questionTextId: "Apa yang seharusnya diucapkan seorang Muslim saat memasuki rumah?",
    optionsId: ["Bismillah", "Assalamu alaikum", "Alhamdulillah", "Masha'Allah"],
    explanationId: "Ucapan salam — \"Assalamu alaikum\" — adalah sunnah saat memasuki rumah, bahkan rumah yang kosong (Quran 24:61).",
    questionTextMs: "Apakah yang patut diucapkan oleh seorang Muslim ketika memasuki rumah?",
    optionsMs: ["Bismillah", "Assalamu alaikum", "Alhamdulillah", "Masha'Allah"],
    explanationMs: "Ucapan salam — \"Assalamu alaikum\" — adalah sunnah ketika memasuki rumah, walaupun rumah yang kosong (Quran 24:61).",
  },
  {
    level: 5, category: "Adab",
    questionText: "Which hand is preferred for eating and drinking?",
    options: ["Left hand", "Right hand", "Either equally", "Both together"], correctIndex: 1,
    explanation: "The Prophet ﷺ taught us to eat and drink with the right hand; the left was associated with shaytan's manner.",
    questionTextId: "Tangan mana yang lebih disukai untuk makan dan minum?",
    optionsId: ["Tangan kiri", "Tangan kanan", "Keduanya sama saja", "Kedua tangan bersama"],
    explanationId: "Nabi ﷺ mengajarkan kita untuk makan dan minum dengan tangan kanan; tangan kiri dikaitkan dengan cara setan.",
    questionTextMs: "Tangan manakah yang diutamakan untuk makan dan minum?",
    optionsMs: ["Tangan kiri", "Tangan kanan", "Kedua-duanya sama", "Kedua tangan bersama"],
    explanationMs: "Nabi ﷺ mengajar kita makan dan minum dengan tangan kanan; tangan kiri dikaitkan dengan cara syaitan.",
  },
  {
    level: 5, category: "Zakah",
    questionText: "Zakat al-Fitr is paid:",
    options: ["Only by the wealthy", "By every Muslim able to, before Eid al-Fitr prayer", "Only on Eid al-Adha", "Once a lifetime"], correctIndex: 1,
    explanation: "Every Muslim who has surplus food gives Zakat al-Fitr on behalf of themselves and dependents before Eid al-Fitr salah.",
    questionTextId: "Zakat al-Fitr dibayarkan:",
    optionsId: ["Hanya oleh orang kaya", "Oleh setiap Muslim yang mampu, sebelum sholat Eid al-Fitr", "Hanya pada Eid al-Adha", "Sekali seumur hidup"],
    explanationId: "Setiap Muslim yang memiliki makanan berlebih membayar Zakat al-Fitr atas nama diri dan tanggungan mereka sebelum sholat Eid al-Fitr.",
    questionTextMs: "Zakat al-Fitr dibayar:",
    optionsMs: ["Hanya oleh orang kaya", "Oleh setiap Muslim yang mampu, sebelum solat Eid al-Fitr", "Hanya pada Eid al-Adha", "Sekali seumur hidup"],
    explanationMs: "Setiap Muslim yang mempunyai makanan lebih membayar Zakat al-Fitr bagi diri mereka dan tanggungan sebelum solat Eid al-Fitr.",
  },
  {
    level: 5, category: "Adab",
    questionText: "What is said before beginning a permissible act like eating?",
    options: ["Alhamdulillah", "Bismillah", "Inna lillahi", "Astaghfirullah"], correctIndex: 1,
    explanation: "\"Bismillah\" — In the name of Allah — is said at the start; \"Alhamdulillah\" follows when finished.",
    questionTextId: "Apa yang diucapkan sebelum memulai perbuatan yang diperbolehkan seperti makan?",
    optionsId: ["Alhamdulillah", "Bismillah", "Inna lillahi", "Astaghfirullah"],
    explanationId: "\"Bismillah\" — Dengan nama Allah — diucapkan di awal; \"Alhamdulillah\" diucapkan setelah selesai.",
    questionTextMs: "Apakah yang diucapkan sebelum memulakan perbuatan yang dibenarkan seperti makan?",
    optionsMs: ["Alhamdulillah", "Bismillah", "Inna lillahi", "Astaghfirullah"],
    explanationMs: "\"Bismillah\" — Dengan nama Allah — diucapkan di permulaan; \"Alhamdulillah\" diucapkan setelah selesai.",
  },
  {
    level: 5, category: "Hajj",
    questionText: "How many times does a pilgrim circle the Ka'bah in tawaf?",
    options: ["3", "5", "7", "10"], correctIndex: 2,
    explanation: "Tawaf consists of seven circuits around the Ka'bah, beginning and ending at the Black Stone.",
    questionTextId: "Berapa kali jamaah haji mengelilingi Ka'bah dalam tawaf?",
    optionsId: ["3", "5", "7", "10"],
    explanationId: "Tawaf terdiri dari tujuh putaran mengelilingi Ka'bah, dimulai dan diakhiri di Hajar Aswad.",
    questionTextMs: "Berapakah kali jemaah haji mengelilingi Ka'bah dalam tawaf?",
    optionsMs: ["3", "5", "7", "10"],
    explanationMs: "Tawaf terdiri daripada tujuh pusingan mengelilingi Ka'bah, bermula dan berakhir di Hajar Aswad.",
  },

  // ── Level 6 — Names & Attributes / Aqidah Deepened ───────────
  {
    level: 6, category: "Aqidah",
    questionText: "How many \"Beautiful Names\" of Allah (Asma'ul Husna) are commonly enumerated?",
    options: ["77", "99", "100", "114"], correctIndex: 1,
    explanation: "The Prophet ﷺ said Allah has 99 names; whoever enumerates them will enter Paradise (Bukhari & Muslim).",
    questionTextId: "Berapa banyak \"Nama-Nama Indah\" Allah (Asma'ul Husna) yang umum disebutkan?",
    optionsId: ["77", "99", "100", "114"],
    explanationId: "Nabi ﷺ bersabda Allah memiliki 99 nama; siapa yang menghafalnya akan masuk surga (Bukhari & Muslim).",
    questionTextMs: "Berapakah \"Nama-Nama Indah\" Allah (Asma'ul Husna) yang biasa disenaraikan?",
    optionsMs: ["77", "99", "100", "114"],
    explanationMs: "Nabi ﷺ bersabda Allah mempunyai 99 nama; sesiapa yang menghafalnya akan masuk syurga (Bukhari & Muslim).",
  },
  {
    level: 6, category: "Aqidah",
    questionText: "Which name of Allah means \"The Most Merciful\" in the broadest, all-encompassing sense?",
    options: ["Ar-Rahim", "Ar-Rahman", "Al-Wadud", "Al-Karim"], correctIndex: 1,
    explanation: "Ar-Rahman denotes Allah's mercy that encompasses all creation; Ar-Rahim is mercy specifically for the believers.",
    questionTextId: "Nama Allah mana yang berarti \"Yang Maha Pengasih\" dalam arti paling luas?",
    optionsId: ["Ar-Rahim", "Ar-Rahman", "Al-Wadud", "Al-Karim"],
    explanationId: "Ar-Rahman menunjukkan rahmat Allah yang meliputi seluruh ciptaan; Ar-Rahim adalah rahmat khusus untuk orang beriman.",
    questionTextMs: "Nama Allah manakah yang bermaksud \"Yang Maha Pemurah\" dalam erti yang paling luas?",
    optionsMs: ["Ar-Rahim", "Ar-Rahman", "Al-Wadud", "Al-Karim"],
    explanationMs: "Ar-Rahman menunjukkan rahmat Allah yang merangkumi seluruh ciptaan; Ar-Rahim adalah rahmat khusus untuk orang mukmin.",
  },
  {
    level: 6, category: "Aqidah",
    questionText: "Tawhid al-Uluhiyyah refers to:",
    options: ["Oneness of Allah's lordship over creation", "Oneness of Allah's right to be worshipped", "Oneness of Allah's names and attributes", "Oneness of the Muslim community"], correctIndex: 1,
    explanation: "Uluhiyyah is directing all worship to Allah alone; Rububiyyah is His sole lordship; Asma' wa Sifat is His names/attributes.",
    questionTextId: "Tawhid al-Uluhiyyah merujuk kepada:",
    optionsId: ["Keesaan ketuhanan Allah atas ciptaan", "Keesaan hak Allah untuk disembah", "Keesaan nama dan sifat Allah", "Keesaan komunitas Muslim"],
    explanationId: "Uluhiyyah adalah mengarahkan seluruh ibadah hanya kepada Allah; Rububiyyah adalah ketuhanan tunggal-Nya; Asma' wa Sifat adalah nama dan sifat-Nya.",
    questionTextMs: "Tawhid al-Uluhiyyah merujuk kepada:",
    optionsMs: ["Keesaan ketuhanan Allah ke atas ciptaan", "Keesaan hak Allah untuk disembah", "Keesaan nama dan sifat Allah", "Keesaan komuniti Muslim"],
    explanationMs: "Uluhiyyah adalah mengarahkan semua ibadah kepada Allah semata; Rububiyyah adalah ketuhanan tunggal-Nya; Asma' wa Sifat adalah nama dan sifat-Nya.",
  },
  {
    level: 6, category: "Aqidah",
    questionText: "Which is the gravest sin in Islam, unforgiven if one dies upon it?",
    options: ["Backbiting", "Shirk (associating partners with Allah)", "Missing Hajj", "Eating haram"], correctIndex: 1,
    explanation: "Allah says He does not forgive shirk if one dies upon it, but forgives anything less for whom He wills (Quran 4:48).",
    questionTextId: "Dosa apa yang paling besar dalam Islam, yang tidak diampuni jika seseorang meninggal dalam keadaan itu?",
    optionsId: ["Ghibah", "Syirik (menyekutukan Allah)", "Tidak pergi Haji", "Makan yang haram"],
    explanationId: "Allah berfirman Dia tidak mengampuni syirik jika seseorang meninggal dalam keadaan itu, tetapi mengampuni selain itu bagi siapa yang Dia kehendaki (Quran 4:48).",
    questionTextMs: "Apakah dosa yang paling besar dalam Islam, yang tidak diampuni jika seseorang meninggal dalam keadaan itu?",
    optionsMs: ["Mengumpat", "Syirik (mensyirikkan Allah)", "Tidak pergi Haji", "Memakan yang haram"],
    explanationMs: "Allah berfirman Dia tidak mengampuni syirik jika seseorang meninggal dalam keadaan itu, tetapi mengampuni selain itu bagi sesiapa yang Dia kehendaki (Quran 4:48).",
  },
  {
    level: 6, category: "Aqidah",
    questionText: "Belief in Qadar means belief in:",
    options: ["Free will only", "Allah's decree and predestination", "Astrology", "The unseen jinn"], correctIndex: 1,
    explanation: "Qadar — Allah's divine decree — is the sixth pillar of iman alongside belief in Allah, angels, books, messengers, and the Last Day.",
    questionTextId: "Iman kepada Qadar berarti percaya pada:",
    optionsId: ["Kehendak bebas saja", "Takdir dan ketetapan Allah", "Astrologi", "Jin yang ghaib"],
    explanationId: "Qadar — ketetapan ilahi Allah — adalah rukun iman keenam, bersama iman kepada Allah, malaikat, kitab, rasul, dan Hari Akhir.",
    questionTextMs: "Beriman kepada Qadar bermaksud percaya kepada:",
    optionsMs: ["Kehendak bebas sahaja", "Qada dan qadar Allah", "Astrologi", "Jin yang ghaib"],
    explanationMs: "Qadar — ketetapan ilahi Allah — adalah rukun iman keenam, bersama iman kepada Allah, malaikat, kitab, rasul, dan Hari Akhir.",
  },
  {
    level: 6, category: "Aqidah",
    questionText: "How many books of revelation are mentioned by name in the Quran?",
    options: ["3", "4", "5", "7"], correctIndex: 1,
    explanation: "Four are named: Tawrat (Musa), Zabur (Dawud), Injil (Isa), and Quran (Muhammad ﷺ); the Suhuf of Ibrahim/Musa are also referenced.",
    questionTextId: "Berapa kitab wahyu yang disebutkan namanya dalam Al-Quran?",
    optionsId: ["3", "4", "5", "7"],
    explanationId: "Empat disebutkan namanya: Tawrat (Musa), Zabur (Dawud), Injil (Isa), dan Al-Quran (Muhammad ﷺ); Suhuf Ibrahim/Musa juga disebutkan.",
    questionTextMs: "Berapakah kitab wahyu yang disebutkan namanya dalam Al-Quran?",
    optionsMs: ["3", "4", "5", "7"],
    explanationMs: "Empat disebutkan namanya: Tawrat (Musa), Zabur (Dawud), Injil (Isa), dan Al-Quran (Muhammad ﷺ); Suhuf Ibrahim/Musa juga dirujuk.",
  },
  {
    level: 6, category: "Aqidah",
    questionText: "Which angel is responsible for blowing the trumpet on the Day of Judgement?",
    options: ["Jibril", "Mika'il", "Israfil", "Izra'il"], correctIndex: 2,
    explanation: "Israfil (a.s.) is appointed to blow the trumpet (As-Sur) marking the end of the world and the resurrection.",
    questionTextId: "Malaikat mana yang bertugas meniup sangkakala pada Hari Kiamat?",
    optionsId: ["Jibril", "Mika'il", "Israfil", "Izra'il"],
    explanationId: "Israfil (a.s.) ditugaskan untuk meniup sangkakala (As-Sur) yang menandai akhir dunia dan kebangkitan.",
    questionTextMs: "Malaikat manakah yang bertanggungjawab meniup sangkakala pada Hari Kiamat?",
    optionsMs: ["Jibril", "Mika'il", "Israfil", "Izra'il"],
    explanationMs: "Israfil (a.s.) ditugaskan untuk meniup sangkakala (As-Sur) yang menandakan akhir dunia dan kebangkitan.",
  },
  {
    level: 6, category: "Aqidah",
    questionText: "Which angel is responsible for taking souls at death?",
    options: ["Jibril", "Malak al-Mawt", "Munkar", "Ridwan"], correctIndex: 1,
    explanation: "Malak al-Mawt — the Angel of Death — is referred to in Surah As-Sajdah 32:11.",
    questionTextId: "Malaikat mana yang bertugas mencabut nyawa saat kematian?",
    optionsId: ["Jibril", "Malak al-Mawt", "Munkar", "Ridwan"],
    explanationId: "Malak al-Mawt — Malaikat Maut — disebutkan dalam Surah As-Sajdah 32:11.",
    questionTextMs: "Malaikat manakah yang bertanggungjawab mencabut nyawa ketika kematian?",
    optionsMs: ["Jibril", "Malak al-Mawt", "Munkar", "Ridwan"],
    explanationMs: "Malak al-Mawt — Malaikat Maut — disebut dalam Surah As-Sajdah 32:11.",
  },
  {
    level: 6, category: "Aqidah",
    questionText: "Jinn were created from:",
    options: ["Clay", "Light", "Smokeless fire", "Water"], correctIndex: 2,
    explanation: "Allah created jinn from a smokeless flame of fire (Quran 55:15); angels from light, and humans from clay.",
    questionTextId: "Jin diciptakan dari:",
    optionsId: ["Tanah liat", "Cahaya", "Api yang tidak berasap", "Air"],
    explanationId: "Allah menciptakan jin dari nyala api yang tidak berasap (Quran 55:15); malaikat dari cahaya, dan manusia dari tanah liat.",
    questionTextMs: "Jin dicipta daripada:",
    optionsMs: ["Tanah liat", "Cahaya", "Api yang tidak berasap", "Air"],
    explanationMs: "Allah mencipta jin daripada nyala api yang tidak berasap (Quran 55:15); malaikat daripada cahaya, dan manusia daripada tanah liat.",
  },
  {
    level: 6, category: "Aqidah",
    questionText: "The bridge over Hellfire that all must cross on the Day of Judgement is called:",
    options: ["As-Sirat", "Al-Mizan", "Al-Hawd", "Al-Kawthar"], correctIndex: 0,
    explanation: "As-Sirat is the bridge stretched over Jahannam; Al-Mizan is the scale, Al-Hawd is the Prophet's ﷺ pond, and Al-Kawthar is a river in Paradise.",
    questionTextId: "Jembatan di atas neraka yang harus dilalui semua orang pada Hari Kiamat disebut:",
    optionsId: ["As-Sirat", "Al-Mizan", "Al-Hawd", "Al-Kawthar"],
    explanationId: "As-Sirat adalah jembatan yang terbentang di atas Jahannam; Al-Mizan adalah neraca, Al-Hawd adalah telaga Nabi ﷺ, dan Al-Kawthar adalah sungai di surga.",
    questionTextMs: "Titi di atas neraka yang semua orang mesti lalui pada Hari Kiamat dinamakan:",
    optionsMs: ["As-Sirat", "Al-Mizan", "Al-Hawd", "Al-Kawthar"],
    explanationMs: "As-Sirat adalah titi yang terbentang di atas Jahannam; Al-Mizan adalah neraca, Al-Hawd adalah telaga Nabi ﷺ, dan Al-Kawthar adalah sungai di syurga.",
  },

  // ── Level 7 — Quran Advanced ─────────────────────────────────
  {
    level: 7, category: "Quran",
    questionText: "Which is the shortest Surah in the Quran?",
    options: ["Al-Ikhlas", "Al-Asr", "Al-Kawthar", "An-Nas"], correctIndex: 2,
    explanation: "Surah Al-Kawthar has only 3 verses, making it the shortest Surah.",
    questionTextId: "Surah apa yang paling pendek dalam Al-Quran?",
    optionsId: ["Al-Ikhlas", "Al-Asr", "Al-Kawthar", "An-Nas"],
    explanationId: "Surah Al-Kawthar hanya memiliki 3 ayat, menjadikannya Surah terpendek.",
    questionTextMs: "Surah manakah yang paling pendek dalam Al-Quran?",
    optionsMs: ["Al-Ikhlas", "Al-Asr", "Al-Kawthar", "An-Nas"],
    explanationMs: "Surah Al-Kawthar hanya mempunyai 3 ayat, menjadikannya Surah yang paling pendek.",
  },
  {
    level: 7, category: "Quran",
    questionText: "Which Surah does NOT begin with Bismillah?",
    options: ["Al-Baqarah", "At-Tawbah", "Yasin", "Al-Mulk"], correctIndex: 1,
    explanation: "Surah At-Tawbah (Bara'ah) is the only Surah that does not open with Bismillahir-Rahmanir-Rahim.",
    questionTextId: "Surah mana yang TIDAK dimulai dengan Bismillah?",
    optionsId: ["Al-Baqarah", "At-Tawbah", "Yasin", "Al-Mulk"],
    explanationId: "Surah At-Tawbah (Bara'ah) adalah satu-satunya Surah yang tidak diawali dengan Bismillahir-Rahmanir-Rahim.",
    questionTextMs: "Surah manakah yang TIDAK dimulai dengan Bismillah?",
    optionsMs: ["Al-Baqarah", "At-Tawbah", "Yasin", "Al-Mulk"],
    explanationMs: "Surah At-Tawbah (Bara'ah) adalah satu-satunya Surah yang tidak dibuka dengan Bismillahir-Rahmanir-Rahim.",
  },
  {
    level: 7, category: "Quran",
    questionText: "Ayat al-Kursi is found in which Surah?",
    options: ["Al-Imran", "Al-Baqarah (verse 255)", "An-Nisa", "Al-Ma'idah"], correctIndex: 1,
    explanation: "Ayat al-Kursi is verse 255 of Surah Al-Baqarah and is the greatest verse in the Quran (Muslim).",
    questionTextId: "Ayat al-Kursi terdapat dalam Surah mana?",
    optionsId: ["Al-Imran", "Al-Baqarah (ayat 255)", "An-Nisa", "Al-Ma'idah"],
    explanationId: "Ayat al-Kursi adalah ayat 255 Surah Al-Baqarah dan merupakan ayat terbesar dalam Al-Quran (Muslim).",
    questionTextMs: "Ayat al-Kursi terdapat dalam Surah manakah?",
    optionsMs: ["Al-Imran", "Al-Baqarah (ayat 255)", "An-Nisa", "Al-Ma'idah"],
    explanationMs: "Ayat al-Kursi adalah ayat 255 Surah Al-Baqarah dan merupakan ayat yang paling agung dalam Al-Quran (Muslim).",
  },
  {
    level: 7, category: "Quran",
    questionText: "Which Surah is named after a metal mentioned in it?",
    options: ["Al-Hadid (Iron)", "An-Nahl (Bee)", "Al-Fil (Elephant)", "An-Naml (Ant)"], correctIndex: 0,
    explanation: "Surah Al-Hadid — \"Iron\" — references the iron Allah sent down with great strength (verse 25).",
    questionTextId: "Surah mana yang dinamai dari logam yang disebutkan di dalamnya?",
    optionsId: ["Al-Hadid (Besi)", "An-Nahl (Lebah)", "Al-Fil (Gajah)", "An-Naml (Semut)"],
    explanationId: "Surah Al-Hadid — \"Besi\" — merujuk pada besi yang diturunkan Allah dengan kekuatan yang besar (ayat 25).",
    questionTextMs: "Surah manakah yang dinamakan sempena logam yang disebut di dalamnya?",
    optionsMs: ["Al-Hadid (Besi)", "An-Nahl (Lebah)", "Al-Fil (Gajah)", "An-Naml (Semut)"],
    explanationMs: "Surah Al-Hadid — \"Besi\" — merujuk kepada besi yang Allah turunkan dengan kekuatan yang besar (ayat 25).",
  },
  {
    level: 7, category: "Quran",
    questionText: "How many Surahs in the Quran are named after prophets?",
    options: ["4", "6", "8", "10"], correctIndex: 1,
    explanation: "Six Surahs are named after prophets: Yunus, Hud, Yusuf, Ibrahim, Muhammad, and Nuh.",
    questionTextId: "Berapa Surah dalam Al-Quran yang dinamai dari nama nabi?",
    optionsId: ["4", "6", "8", "10"],
    explanationId: "Enam Surah dinamai dari nabi: Yunus, Hud, Yusuf, Ibrahim, Muhammad, dan Nuh.",
    questionTextMs: "Berapakah Surah dalam Al-Quran yang dinamakan sempena nama nabi?",
    optionsMs: ["4", "6", "8", "10"],
    explanationMs: "Enam Surah dinamakan sempena nabi: Yunus, Hud, Yusuf, Ibrahim, Muhammad, dan Nuh.",
  },
  {
    level: 7, category: "Quran",
    questionText: "Surah Al-Fatihah consists of how many verses?",
    options: ["5", "6", "7", "8"], correctIndex: 2,
    explanation: "Al-Fatihah has 7 verses, also called As-Sab' al-Mathani — \"the seven oft-repeated\" (Quran 15:87).",
    questionTextId: "Surah Al-Fatihah terdiri dari berapa ayat?",
    optionsId: ["5", "6", "7", "8"],
    explanationId: "Al-Fatihah memiliki 7 ayat, juga disebut As-Sab' al-Mathani — \"tujuh ayat yang berulang\" (Quran 15:87).",
    questionTextMs: "Surah Al-Fatihah terdiri daripada berapa ayat?",
    optionsMs: ["5", "6", "7", "8"],
    explanationMs: "Al-Fatihah mempunyai 7 ayat, juga dikenali sebagai As-Sab' al-Mathani — \"tujuh yang berulang\" (Quran 15:87).",
  },
  {
    level: 7, category: "Quran",
    questionText: "Which Surah is recited together with Al-Falaq for protection (Al-Mu'awwidhatayn)?",
    options: ["Al-Ikhlas", "An-Nas", "Al-Kafirun", "Al-Asr"], correctIndex: 1,
    explanation: "Al-Falaq and An-Nas form Al-Mu'awwidhatayn — the two Surahs of refuge — recited morning, evening, and before sleep.",
    questionTextId: "Surah mana yang dibaca bersama Al-Falaq untuk perlindungan (Al-Mu'awwidhatayn)?",
    optionsId: ["Al-Ikhlas", "An-Nas", "Al-Kafirun", "Al-Asr"],
    explanationId: "Al-Falaq dan An-Nas membentuk Al-Mu'awwidhatayn — dua Surah perlindungan — yang dibaca pagi, petang, dan sebelum tidur.",
    questionTextMs: "Surah manakah yang dibaca bersama Al-Falaq untuk perlindungan (Al-Mu'awwidhatayn)?",
    optionsMs: ["Al-Ikhlas", "An-Nas", "Al-Kafirun", "Al-Asr"],
    explanationMs: "Al-Falaq dan An-Nas membentuk Al-Mu'awwidhatayn — dua Surah perlindungan — yang dibaca pagi, petang, dan sebelum tidur.",
  },
  {
    level: 7, category: "Quran",
    questionText: "Surah Al-Ikhlas is described by the Prophet ﷺ as equal to:",
    options: ["A quarter of the Quran", "A third of the Quran", "Half of the Quran", "The whole Quran"], correctIndex: 1,
    explanation: "The Prophet ﷺ said Qul Huwa Allahu Ahad equals one-third of the Quran (Bukhari) because of its pure declaration of Tawhid.",
    questionTextId: "Surah Al-Ikhlas digambarkan oleh Nabi ﷺ setara dengan:",
    optionsId: ["Seperempat Al-Quran", "Sepertiga Al-Quran", "Setengah Al-Quran", "Seluruh Al-Quran"],
    explanationId: "Nabi ﷺ bersabda Qul Huwa Allahu Ahad setara dengan sepertiga Al-Quran (Bukhari) karena pernyataan murni Tauhidnya.",
    questionTextMs: "Surah Al-Ikhlas digambarkan oleh Nabi ﷺ sebanding dengan:",
    optionsMs: ["Satu perempat Al-Quran", "Satu pertiga Al-Quran", "Separuh Al-Quran", "Seluruh Al-Quran"],
    explanationMs: "Nabi ﷺ bersabda Qul Huwa Allahu Ahad bersamaan dengan satu pertiga Al-Quran (Bukhari) kerana pernyataan Tauhid yang murni.",
  },
  {
    level: 7, category: "Quran",
    questionText: "Which Surah begins with \"Tabarakalladhi\" and is recommended to read before sleep?",
    options: ["Al-Mulk", "As-Sajdah", "Al-Waqi'ah", "Ar-Rahman"], correctIndex: 0,
    explanation: "Surah Al-Mulk (\"Tabarakalladhi biyadihil Mulk\") intercedes for the one who recites it (Tirmidhi).",
    questionTextId: "Surah mana yang diawali dengan \"Tabarakalladhi\" dan dianjurkan dibaca sebelum tidur?",
    optionsId: ["Al-Mulk", "As-Sajdah", "Al-Waqi'ah", "Ar-Rahman"],
    explanationId: "Surah Al-Mulk (\"Tabarakalladhi biyadihil Mulk\") akan memberi syafaat bagi orang yang membacanya (Tirmidzi).",
    questionTextMs: "Surah manakah yang bermula dengan \"Tabarakalladhi\" dan dianjurkan dibaca sebelum tidur?",
    optionsMs: ["Al-Mulk", "As-Sajdah", "Al-Waqi'ah", "Ar-Rahman"],
    explanationMs: "Surah Al-Mulk (\"Tabarakalladhi biyadihil Mulk\") akan memberi syafaat bagi orang yang membacanya (Tirmidhi).",
  },
  {
    level: 7, category: "Quran",
    questionText: "What is the term for the prostration prescribed when reciting certain verses of the Quran?",
    options: ["Sujud as-Sahw", "Sujud at-Tilawah", "Sujud ash-Shukr", "Sujud at-Taqwa"], correctIndex: 1,
    explanation: "Sujud at-Tilawah is the prostration of recitation, performed at specific verses of sajdah marked in the mushaf.",
    questionTextId: "Apa istilah untuk sujud yang dilakukan saat membaca ayat-ayat tertentu dalam Al-Quran?",
    optionsId: ["Sujud as-Sahw", "Sujud at-Tilawah", "Sujud ash-Shukr", "Sujud at-Taqwa"],
    explanationId: "Sujud at-Tilawah adalah sujud bacaan, dilakukan pada ayat-ayat sajdah tertentu yang ditandai dalam mushaf.",
    questionTextMs: "Apakah istilah untuk sujud yang dilakukan semasa membaca ayat-ayat tertentu dalam Al-Quran?",
    optionsMs: ["Sujud as-Sahw", "Sujud at-Tilawah", "Sujud ash-Shukr", "Sujud at-Taqwa"],
    explanationMs: "Sujud at-Tilawah adalah sujud bacaan, dilakukan pada ayat-ayat sajdah tertentu yang ditandakan dalam mushaf.",
  },

  // ── Level 8 — Seerah Advanced ────────────────────────────────
  {
    level: 8, category: "Seerah",
    questionText: "What was the name of the Prophet's ﷺ father?",
    options: ["Abdul-Muttalib", "Abdullah", "Abu Talib", "Hamzah"], correctIndex: 1,
    explanation: "Abdullah ibn Abdul-Muttalib died before the Prophet ﷺ was born.",
    questionTextId: "Siapakah nama ayah Nabi ﷺ?",
    optionsId: ["Abdul-Muttalib", "Abdullah", "Abu Talib", "Hamzah"],
    explanationId: "Abdullah ibn Abdul-Muttalib wafat sebelum Nabi ﷺ dilahirkan.",
    questionTextMs: "Siapakah nama ayah Nabi ﷺ?",
    optionsMs: ["Abdul-Muttalib", "Abdullah", "Abu Talib", "Hamzah"],
    explanationMs: "Abdullah ibn Abdul-Muttalib meninggal dunia sebelum Nabi ﷺ dilahirkan.",
  },
  {
    level: 8, category: "Seerah",
    questionText: "Who was the Prophet's ﷺ mother?",
    options: ["Halimah as-Sa'diyyah", "Aminah bint Wahb", "Khadijah bint Khuwaylid", "Fatimah bint Asad"], correctIndex: 1,
    explanation: "Aminah bint Wahb passed away when the Prophet ﷺ was about six years old.",
    questionTextId: "Siapakah ibu Nabi ﷺ?",
    optionsId: ["Halimah as-Sa'diyyah", "Aminah binti Wahb", "Khadijah binti Khuwaylid", "Fatimah binti Asad"],
    explanationId: "Aminah binti Wahb wafat ketika Nabi ﷺ berusia sekitar enam tahun.",
    questionTextMs: "Siapakah ibu Nabi ﷺ?",
    optionsMs: ["Halimah as-Sa'diyyah", "Aminah binti Wahb", "Khadijah binti Khuwaylid", "Fatimah binti Asad"],
    explanationMs: "Aminah binti Wahb meninggal dunia ketika Nabi ﷺ berusia lebih kurang enam tahun.",
  },
  {
    level: 8, category: "Seerah",
    questionText: "Which uncle of the Prophet ﷺ raised him after his grandfather's death?",
    options: ["Hamzah", "Al-Abbas", "Abu Lahab", "Abu Talib"], correctIndex: 3,
    explanation: "Abu Talib, the Prophet's ﷺ paternal uncle, took him into his care and protected him in Makkah.",
    questionTextId: "Paman Nabi ﷺ mana yang merawatnya setelah kakeknya wafat?",
    optionsId: ["Hamzah", "Al-Abbas", "Abu Lahab", "Abu Talib"],
    explanationId: "Abu Talib, paman dari pihak ayah Nabi ﷺ, mengambilnya dalam perlindungan dan melindunginya di Makkah.",
    questionTextMs: "Bapa saudara Nabi ﷺ manakah yang membesarkan baginda selepas datuknya meninggal?",
    optionsMs: ["Hamzah", "Al-Abbas", "Abu Lahab", "Abu Talib"],
    explanationMs: "Abu Talib, bapa saudara sebelah ayah Nabi ﷺ, mengambilnya dalam jagaannya dan melindunginya di Makkah.",
  },
  {
    level: 8, category: "Seerah",
    questionText: "Which year is known as \"the Year of Sorrow\" ('Am al-Huzn)?",
    options: ["The year Khadijah and Abu Talib died", "The year of the Hijrah", "The year of Badr", "The year of the Conquest"], correctIndex: 0,
    explanation: "Both Khadijah (r.a.) and Abu Talib died in the same year (~10th year of prophethood), bringing immense grief to the Prophet ﷺ.",
    questionTextId: "Tahun mana yang dikenal sebagai \"Tahun Kesedihan\" ('Am al-Huzn)?",
    optionsId: ["Tahun wafatnya Khadijah dan Abu Talib", "Tahun Hijrah", "Tahun Perang Badr", "Tahun Penaklukan"],
    explanationId: "Khadijah (r.a.) dan Abu Talib keduanya wafat pada tahun yang sama (~tahun ke-10 kenabian), membawa kesedihan yang mendalam bagi Nabi ﷺ.",
    questionTextMs: "Tahun manakah yang dikenali sebagai \"Tahun Kesedihan\" ('Am al-Huzn)?",
    optionsMs: ["Tahun kewafatan Khadijah dan Abu Talib", "Tahun Hijrah", "Tahun Perang Badr", "Tahun Penaklukan"],
    explanationMs: "Khadijah (r.a.) dan Abu Talib keduanya meninggal dunia pada tahun yang sama (~tahun ke-10 kenabian), membawa kesedihan yang mendalam kepada Nabi ﷺ.",
  },
  {
    level: 8, category: "Seerah",
    questionText: "Which battle did the Muslims dig a trench around Madinah for defense?",
    options: ["Badr", "Uhud", "Khandaq (Ahzab)", "Tabuk"], correctIndex: 2,
    explanation: "On Salman al-Farisi's (r.a.) advice, the Muslims dug a khandaq (trench) before the Battle of Ahzab in 5 AH.",
    questionTextId: "Dalam perang apa umat Islam menggali parit di sekitar Madinah untuk pertahanan?",
    optionsId: ["Badr", "Uhud", "Khandaq (Ahzab)", "Tabuk"],
    explanationId: "Atas saran Salman al-Farisi (r.a.), kaum Muslim menggali khandaq (parit) sebelum Perang Ahzab pada 5 H.",
    questionTextMs: "Dalam perang manakah umat Islam menggali parit di sekeliling Madinah untuk pertahanan?",
    optionsMs: ["Badr", "Uhud", "Khandaq (Ahzab)", "Tabuk"],
    explanationMs: "Atas cadangan Salman al-Farisi (r.a.), umat Islam menggali khandaq (parit) sebelum Perang Ahzab pada 5H.",
  },
  {
    level: 8, category: "Seerah",
    questionText: "In what year (Hijri) did the Conquest of Makkah occur?",
    options: ["6 AH", "8 AH", "10 AH", "11 AH"], correctIndex: 1,
    explanation: "Fath Makkah took place in Ramadan, 8 AH, after the Quraysh broke the Treaty of Hudaybiyyah.",
    questionTextId: "Pada tahun berapa (Hijriah) penaklukan Makkah terjadi?",
    optionsId: ["6 H", "8 H", "10 H", "11 H"],
    explanationId: "Fath Makkah terjadi pada bulan Ramadan, 8 H, setelah Quraisy melanggar Perjanjian Hudaybiyyah.",
    questionTextMs: "Pada tahun berapakah (Hijri) penaklukan Makkah berlaku?",
    optionsMs: ["6H", "8H", "10H", "11H"],
    explanationMs: "Fath Makkah berlaku pada bulan Ramadan, 8H, selepas Quraisy melanggar Perjanjian Hudaybiyyah.",
  },
  {
    level: 8, category: "Seerah",
    questionText: "Who was the first child to accept Islam?",
    options: ["Hasan ibn Ali", "Ali ibn Abi Talib", "Zayd ibn Harithah", "Usamah ibn Zayd"], correctIndex: 1,
    explanation: "Ali ibn Abi Talib (r.a.), then about 10 years old, was the first child to embrace Islam.",
    questionTextId: "Siapakah anak pertama yang memeluk Islam?",
    optionsId: ["Hasan ibn Ali", "Ali ibn Abi Talib", "Zayd ibn Harithah", "Usamah ibn Zayd"],
    explanationId: "Ali ibn Abi Talib (r.a.), yang waktu itu berusia sekitar 10 tahun, adalah anak pertama yang memeluk Islam.",
    questionTextMs: "Siapakah kanak-kanak pertama yang memeluk Islam?",
    optionsMs: ["Hasan ibn Ali", "Ali ibn Abi Talib", "Zayd ibn Harithah", "Usamah ibn Zayd"],
    explanationMs: "Ali ibn Abi Talib (r.a.), yang ketika itu berusia lebih kurang 10 tahun, adalah kanak-kanak pertama yang memeluk Islam.",
  },
  {
    level: 8, category: "Seerah",
    questionText: "Who was the first freed slave to accept Islam, later the muezzin of the Prophet ﷺ?",
    options: ["Salman al-Farisi", "Bilal ibn Rabah", "Suhayb ar-Rumi", "Zayd ibn Harithah"], correctIndex: 1,
    explanation: "Bilal ibn Rabah (r.a.) was tortured for his faith, freed by Abu Bakr (r.a.), and became the first muezzin of Islam.",
    questionTextId: "Siapakah budak yang dimerdekakan pertama yang memeluk Islam, kemudian menjadi muazin Nabi ﷺ?",
    optionsId: ["Salman al-Farisi", "Bilal ibn Rabah", "Suhayb ar-Rumi", "Zayd ibn Harithah"],
    explanationId: "Bilal ibn Rabah (r.a.) disiksa karena imannya, dimerdekakan oleh Abu Bakr (r.a.), dan menjadi muazin pertama Islam.",
    questionTextMs: "Siapakah hamba yang dimerdekakan pertama yang memeluk Islam, kemudian menjadi muazin Nabi ﷺ?",
    optionsMs: ["Salman al-Farisi", "Bilal ibn Rabah", "Suhayb ar-Rumi", "Zayd ibn Harithah"],
    explanationMs: "Bilal ibn Rabah (r.a.) disiksa kerana imannya, dimerdekakan oleh Abu Bakr (r.a.), dan menjadi muazin pertama Islam.",
  },
  {
    level: 8, category: "Seerah",
    questionText: "The Treaty of Hudaybiyyah was signed in what year?",
    options: ["2 AH", "5 AH", "6 AH", "9 AH"], correctIndex: 2,
    explanation: "The treaty was signed in 6 AH and is described in the Quran as a \"clear victory\" (Surah Al-Fath).",
    questionTextId: "Perjanjian Hudaybiyyah ditandatangani pada tahun berapa?",
    optionsId: ["2 H", "5 H", "6 H", "9 H"],
    explanationId: "Perjanjian ini ditandatangani pada 6 H dan digambarkan dalam Al-Quran sebagai \"kemenangan yang nyata\" (Surah Al-Fath).",
    questionTextMs: "Perjanjian Hudaybiyyah ditandatangani pada tahun berapakah?",
    optionsMs: ["2H", "5H", "6H", "9H"],
    explanationMs: "Perjanjian ini ditandatangani pada 6H dan digambarkan dalam Al-Quran sebagai \"kemenangan yang nyata\" (Surah Al-Fath).",
  },
  {
    level: 8, category: "Seerah",
    questionText: "The Prophet ﷺ delivered his Farewell Sermon at:",
    options: ["Mount Hira", "Mount Uhud", "Arafah, during the Farewell Hajj", "The Cave of Thawr"], correctIndex: 2,
    explanation: "He ﷺ delivered Khutbat al-Wada' on the plain of Arafah during Hajjat al-Wada' (10 AH).",
    questionTextId: "Nabi ﷺ menyampaikan Khutbah Wada'nya di:",
    optionsId: ["Gunung Hira", "Gunung Uhud", "Arafah, saat Haji Wada'", "Gua Tsaur"],
    explanationId: "Beliau ﷺ menyampaikan Khutbat al-Wada' di padang Arafah saat Hajjat al-Wada' (10 H).",
    questionTextMs: "Nabi ﷺ menyampaikan Khutbah Wada'nya di:",
    optionsMs: ["Bukit Hira", "Bukit Uhud", "Arafah, semasa Hajj Wada'", "Gua Thawr"],
    explanationMs: "Baginda ﷺ menyampaikan Khutbat al-Wada' di dataran Arafah semasa Hajjat al-Wada' (10H).",
  },

  // ── Level 9 — Hadith & Companions ────────────────────────────
  {
    level: 9, category: "Hadith",
    questionText: "Which two hadith collections are considered the most authentic (As-Sahihayn)?",
    options: ["Bukhari and Muslim", "Tirmidhi and Abu Dawud", "Nasa'i and Ibn Majah", "Muwatta and Ahmad"], correctIndex: 0,
    explanation: "Sahih al-Bukhari and Sahih Muslim are the two most rigorously authenticated hadith collections in Sunni Islam.",
    questionTextId: "Dua kitab hadits mana yang dianggap paling otentik (As-Sahihayn)?",
    optionsId: ["Bukhari dan Muslim", "Tirmidzi dan Abu Dawud", "Nasa'i dan Ibn Majah", "Muwatta dan Ahmad"],
    explanationId: "Shahih al-Bukhari dan Shahih Muslim adalah dua koleksi hadits yang paling ketat keasliannya dalam Islam Sunni.",
    questionTextMs: "Dua koleksi hadith manakah yang dianggap paling sahih (As-Sahihayn)?",
    optionsMs: ["Bukhari dan Muslim", "Tirmidhi dan Abu Dawud", "Nasa'i dan Ibn Majah", "Muwatta dan Ahmad"],
    explanationMs: "Sahih al-Bukhari dan Sahih Muslim adalah dua koleksi hadith yang paling ketat kesahihannya dalam Islam Sunni.",
  },
  {
    level: 9, category: "Hadith",
    questionText: "Who compiled Sahih al-Bukhari?",
    options: ["Imam Muslim", "Imam Malik", "Imam Muhammad ibn Isma'il al-Bukhari", "Imam Ahmad ibn Hanbal"], correctIndex: 2,
    explanation: "Imam al-Bukhari spent ~16 years compiling and verifying his Sahih, selecting from hundreds of thousands of narrations.",
    questionTextId: "Siapa yang menyusun Shahih al-Bukhari?",
    optionsId: ["Imam Muslim", "Imam Malik", "Imam Muhammad ibn Isma'il al-Bukhari", "Imam Ahmad ibn Hanbal"],
    explanationId: "Imam al-Bukhari menghabiskan ~16 tahun menyusun dan memverifikasi Shahihnya, memilih dari ratusan ribu riwayat.",
    questionTextMs: "Siapakah yang menyusun Sahih al-Bukhari?",
    optionsMs: ["Imam Muslim", "Imam Malik", "Imam Muhammad ibn Isma'il al-Bukhari", "Imam Ahmad ibn Hanbal"],
    explanationMs: "Imam al-Bukhari menghabiskan ~16 tahun menyusun dan mengesahkan Sahihnya, memilih daripada ratusan ribu riwayat.",
  },
  {
    level: 9, category: "Hadith",
    questionText: "What does \"hadith\" literally mean?",
    options: ["Speech / report", "Law", "Path", "Memorization"], correctIndex: 0,
    explanation: "Hadith linguistically means \"speech\" or \"report\"; technically it refers to the sayings, actions, and approvals of the Prophet ﷺ.",
    questionTextId: "Apa arti harfiah kata \"hadits\"?",
    optionsId: ["Ucapan / laporan", "Hukum", "Jalan", "Hafalan"],
    explanationId: "Hadits secara bahasa berarti \"ucapan\" atau \"laporan\"; secara istilah merujuk pada perkataan, perbuatan, dan persetujuan Nabi ﷺ.",
    questionTextMs: "Apakah maksud harfiah perkataan \"hadith\"?",
    optionsMs: ["Ucapan / laporan", "Hukum", "Jalan", "Hafalan"],
    explanationMs: "Hadith dari segi bahasa bermaksud \"ucapan\" atau \"laporan\"; dari segi istilah merujuk kepada perkataan, perbuatan, dan keizinan Nabi ﷺ.",
  },
  {
    level: 9, category: "Hadith",
    questionText: "What is the chain of narrators in a hadith called?",
    options: ["Matn", "Sanad (Isnad)", "Sahih", "Mursal"], correctIndex: 1,
    explanation: "The sanad is the chain of transmission; the matn is the actual text/content of the hadith.",
    questionTextId: "Apa nama rantai perawi dalam sebuah hadits?",
    optionsId: ["Matn", "Sanad (Isnad)", "Sahih", "Mursal"],
    explanationId: "Sanad adalah rantai transmisi; matn adalah teks atau isi sebenarnya dari hadits.",
    questionTextMs: "Apakah nama rantaian perawi dalam sebuah hadith?",
    optionsMs: ["Matn", "Sanad (Isnad)", "Sahih", "Mursal"],
    explanationMs: "Sanad adalah rantaian transmisi; matn adalah teks atau kandungan sebenar hadith.",
  },
  {
    level: 9, category: "Companions",
    questionText: "Which female companion narrated the most hadith from the Prophet ﷺ?",
    options: ["Khadijah (r.a.)", "Aisha (r.a.)", "Hafsa (r.a.)", "Umm Salamah (r.a.)"], correctIndex: 1,
    explanation: "Aisha bint Abi Bakr (r.a.) narrated over 2,200 ahadith and is among the top narrators of all the companions.",
    questionTextId: "Sahabiyah mana yang paling banyak meriwayatkan hadits dari Nabi ﷺ?",
    optionsId: ["Khadijah (r.a.)", "Aisha (r.a.)", "Hafsa (r.a.)", "Umm Salamah (r.a.)"],
    explanationId: "Aisha binti Abi Bakr (r.a.) meriwayatkan lebih dari 2.200 hadits dan termasuk di antara perawi terbanyak dari semua sahabat.",
    questionTextMs: "Sahabiyah manakah yang paling banyak meriwayatkan hadith daripada Nabi ﷺ?",
    optionsMs: ["Khadijah (r.a.)", "Aisha (r.a.)", "Hafsa (r.a.)", "Umm Salamah (r.a.)"],
    explanationMs: "Aisha binti Abi Bakr (r.a.) meriwayatkan lebih daripada 2,200 hadith dan termasuk di kalangan perawi terbesar daripada semua sahabat.",
  },
  {
    level: 9, category: "Companions",
    questionText: "Who is the companion that narrated the most hadith overall?",
    options: ["Abu Hurairah (r.a.)", "Ibn Umar (r.a.)", "Anas ibn Malik (r.a.)", "Ibn Abbas (r.a.)"], correctIndex: 0,
    explanation: "Abu Hurairah (r.a.) narrated over 5,300 ahadith — more than any other companion.",
    questionTextId: "Sahabat mana yang paling banyak meriwayatkan hadits secara keseluruhan?",
    optionsId: ["Abu Hurairah (r.a.)", "Ibn Umar (r.a.)", "Anas ibn Malik (r.a.)", "Ibn Abbas (r.a.)"],
    explanationId: "Abu Hurairah (r.a.) meriwayatkan lebih dari 5.300 hadits — lebih banyak dari sahabat mana pun.",
    questionTextMs: "Sahabat manakah yang paling banyak meriwayatkan hadith keseluruhannya?",
    optionsMs: ["Abu Hurairah (r.a.)", "Ibn Umar (r.a.)", "Anas ibn Malik (r.a.)", "Ibn Abbas (r.a.)"],
    explanationMs: "Abu Hurairah (r.a.) meriwayatkan lebih daripada 5,300 hadith — lebih banyak daripada mana-mana sahabat lain.",
  },
  {
    level: 9, category: "Companions",
    questionText: "Which companion is titled \"the trustworthy of this Ummah\" (Amin al-Ummah)?",
    options: ["Abu Ubaydah ibn al-Jarrah (r.a.)", "Mu'adh ibn Jabal (r.a.)", "Sa'd ibn Mu'adh (r.a.)", "Anas ibn Malik (r.a.)"], correctIndex: 0,
    explanation: "The Prophet ﷺ said \"Every Ummah has a trustworthy one, and the trustworthy of this Ummah is Abu Ubaydah ibn al-Jarrah\" (Bukhari).",
    questionTextId: "Sahabat mana yang bergelar \"yang dapat dipercaya dari Umat ini\" (Amin al-Ummah)?",
    optionsId: ["Abu Ubaydah ibn al-Jarrah (r.a.)", "Mu'adh ibn Jabal (r.a.)", "Sa'd ibn Mu'adh (r.a.)", "Anas ibn Malik (r.a.)"],
    explanationId: "Nabi ﷺ bersabda \"Setiap umat memiliki orang kepercayaan, dan orang kepercayaan umat ini adalah Abu Ubaydah ibn al-Jarrah\" (Bukhari).",
    questionTextMs: "Sahabat manakah yang bergelar \"orang kepercayaan umat ini\" (Amin al-Ummah)?",
    optionsMs: ["Abu Ubaydah ibn al-Jarrah (r.a.)", "Mu'adh ibn Jabal (r.a.)", "Sa'd ibn Mu'adh (r.a.)", "Anas ibn Malik (r.a.)"],
    explanationMs: "Nabi ﷺ bersabda \"Setiap umat mempunyai orang kepercayaan, dan orang kepercayaan umat ini ialah Abu Ubaydah ibn al-Jarrah\" (Bukhari).",
  },
  {
    level: 9, category: "Companions",
    questionText: "Which caliph is known as \"Dhun-Nurayn\" (the possessor of two lights)?",
    options: ["Abu Bakr (r.a.)", "Umar (r.a.)", "Uthman (r.a.)", "Ali (r.a.)"], correctIndex: 2,
    explanation: "Uthman ibn Affan (r.a.) was given this title because he married two of the Prophet's ﷺ daughters, Ruqayyah and Umm Kulthum.",
    questionTextId: "Khalifah mana yang dikenal sebagai \"Dhun-Nurayn\" (pemilik dua cahaya)?",
    optionsId: ["Abu Bakr (r.a.)", "Umar (r.a.)", "Uthman (r.a.)", "Ali (r.a.)"],
    explanationId: "Uthman ibn Affan (r.a.) mendapat gelar ini karena menikahi dua putri Nabi ﷺ, yaitu Ruqayyah dan Umm Kulthum.",
    questionTextMs: "Khalifah manakah yang dikenali sebagai \"Dhun-Nurayn\" (pemilik dua cahaya)?",
    optionsMs: ["Abu Bakr (r.a.)", "Umar (r.a.)", "Uthman (r.a.)", "Ali (r.a.)"],
    explanationMs: "Uthman ibn Affan (r.a.) mendapat gelaran ini kerana berkahwin dengan dua puteri Nabi ﷺ, iaitu Ruqayyah dan Umm Kulthum.",
  },
  {
    level: 9, category: "Companions",
    questionText: "Which companion was titled \"Al-Faruq\" (the one who distinguishes truth from falsehood)?",
    options: ["Abu Bakr (r.a.)", "Umar ibn al-Khattab (r.a.)", "Hamzah (r.a.)", "Bilal (r.a.)"], correctIndex: 1,
    explanation: "Umar ibn al-Khattab (r.a.) was named Al-Faruq for his uncompromising stance between truth and falsehood.",
    questionTextId: "Sahabat mana yang diberi gelar \"Al-Faruq\" (orang yang membedakan kebenaran dari kebatilan)?",
    optionsId: ["Abu Bakr (r.a.)", "Umar ibn al-Khattab (r.a.)", "Hamzah (r.a.)", "Bilal (r.a.)"],
    explanationId: "Umar ibn al-Khattab (r.a.) dinamai Al-Faruq karena sikapnya yang tegas antara kebenaran dan kebatilan.",
    questionTextMs: "Sahabat manakah yang digelar \"Al-Faruq\" (orang yang membezakan kebenaran daripada kebatilan)?",
    optionsMs: ["Abu Bakr (r.a.)", "Umar ibn al-Khattab (r.a.)", "Hamzah (r.a.)", "Bilal (r.a.)"],
    explanationMs: "Umar ibn al-Khattab (r.a.) dinamakan Al-Faruq kerana sikapnya yang tegas antara kebenaran dan kebatilan.",
  },
  {
    level: 9, category: "Hadith",
    questionText: "A hadith narrated through an unbroken chain of trustworthy narrators free from defects is graded:",
    options: ["Da'if (weak)", "Hasan (good)", "Sahih (authentic)", "Mawdu' (fabricated)"], correctIndex: 2,
    explanation: "Sahih is the highest grade — an unbroken chain of upright, precise narrators with no hidden defect or contradiction.",
    questionTextId: "Hadits yang diriwayatkan melalui rantai perawi terpercaya yang tidak terputus dan bebas dari cacat dinilai:",
    optionsId: ["Da'if (lemah)", "Hasan (baik)", "Sahih (otentik)", "Mawdu' (palsu)"],
    explanationId: "Sahih adalah tingkatan tertinggi — rantai perawi yang tidak terputus, jujur, dan tepat tanpa cacat tersembunyi atau kontradiksi.",
    questionTextMs: "Hadith yang diriwayatkan melalui rantaian perawi yang dipercayai, tidak terputus dan bebas dari kecacatan dinilai:",
    optionsMs: ["Da'if (lemah)", "Hasan (baik)", "Sahih (sahih)", "Mawdu' (palsu)"],
    explanationMs: "Sahih adalah gred tertinggi — rantaian perawi yang tidak terputus, jujur, dan tepat tanpa kecacatan tersembunyi atau percanggahan.",
  },

  // ── Level 10 — Advanced Fiqh & Akhlaq ────────────────────────
  {
    level: 10, category: "Fiqh",
    questionText: "Which is NOT one of the four major Sunni schools of jurisprudence (madhahib)?",
    options: ["Hanafi", "Maliki", "Ja'fari", "Shafi'i"], correctIndex: 2,
    explanation: "The four Sunni madhahib are Hanafi, Maliki, Shafi'i, and Hanbali. The Ja'fari school is followed in Shia Islam.",
    questionTextId: "Mana yang BUKAN salah satu dari empat mazhab utama Sunni (madhahib)?",
    optionsId: ["Hanafi", "Maliki", "Ja'fari", "Syafi'i"],
    explanationId: "Empat mazhab Sunni adalah Hanafi, Maliki, Syafi'i, dan Hanbali. Mazhab Ja'fari diikuti dalam Islam Syiah.",
    questionTextMs: "Manakah yang BUKAN salah satu daripada empat mazhab utama Sunni (madhahib)?",
    optionsMs: ["Hanafi", "Maliki", "Ja'fari", "Shafi'i"],
    explanationMs: "Empat mazhab Sunni ialah Hanafi, Maliki, Shafi'i, dan Hanbali. Mazhab Ja'fari diikuti dalam Islam Syiah.",
  },
  {
    level: 10, category: "Fiqh",
    questionText: "What is the nisab for zakah on silver, traditionally?",
    options: ["100 grams", "200 dirhams (~595g of silver)", "1 kg", "5 dinars"], correctIndex: 1,
    explanation: "The classical silver nisab is 200 dirhams, approximately 595 grams of silver.",
    questionTextId: "Berapakah nisab zakah untuk perak secara tradisional?",
    optionsId: ["100 gram", "200 dirham (~595g perak)", "1 kg", "5 dinar"],
    explanationId: "Nisab perak klasik adalah 200 dirham, sekitar 595 gram perak.",
    questionTextMs: "Berapakah nisab zakah untuk perak secara tradisional?",
    optionsMs: ["100 gram", "200 dirham (~595g perak)", "1 kg", "5 dinar"],
    explanationMs: "Nisab perak klasik ialah 200 dirham, lebih kurang 595 gram perak.",
  },
  {
    level: 10, category: "Fiqh",
    questionText: "Which prayer is specifically prescribed when seeking guidance for a decision?",
    options: ["Salat al-Hajah", "Salat al-Istikharah", "Salat at-Tasbih", "Salat al-Awwabin"], correctIndex: 1,
    explanation: "Salat al-Istikharah is two voluntary rak'ahs followed by a specific dua asking Allah for guidance (Bukhari).",
    questionTextId: "Sholat apa yang secara khusus diperintahkan ketika mencari petunjuk untuk suatu keputusan?",
    optionsId: ["Salat al-Hajah", "Salat al-Istikharah", "Salat at-Tasbih", "Salat al-Awwabin"],
    explanationId: "Salat al-Istikharah adalah dua rakaat sunnah diikuti dengan doa khusus memohon petunjuk Allah (Bukhari).",
    questionTextMs: "Solat apakah yang secara khusus dianjurkan ketika mencari petunjuk untuk sesuatu keputusan?",
    optionsMs: ["Salat al-Hajah", "Salat al-Istikharah", "Salat at-Tasbih", "Salat al-Awwabin"],
    explanationMs: "Salat al-Istikharah adalah dua rakaat sunat diikuti dengan doa khusus memohon petunjuk Allah (Bukhari).",
  },
  {
    level: 10, category: "Fiqh",
    questionText: "Tayammum (dry purification) is permitted when:",
    options: ["One is in a hurry", "Water is unavailable or harmful to use", "One is fasting", "One is travelling, regardless of water"], correctIndex: 1,
    explanation: "Tayammum replaces wudu/ghusl when water is absent or its use would cause harm (Quran 4:43, 5:6).",
    questionTextId: "Tayammum (bersuci kering) diperbolehkan ketika:",
    optionsId: ["Seseorang terburu-buru", "Air tidak tersedia atau berbahaya untuk digunakan", "Seseorang sedang berpuasa", "Seseorang bepergian, terlepas dari air"],
    explanationId: "Tayammum menggantikan wudhu/mandi ketika air tidak ada atau penggunaannya akan menyebabkan bahaya (Quran 4:43, 5:6).",
    questionTextMs: "Tayammum (bersuci kering) dibenarkan apabila:",
    optionsMs: ["Seseorang tergesa-gesa", "Air tidak tersedia atau berbahaya untuk digunakan", "Seseorang sedang berpuasa", "Seseorang dalam perjalanan, tanpa mengira ketersediaan air"],
    explanationMs: "Tayammum menggantikan Wudu/mandi ketika air tiada atau penggunaannya akan menyebabkan mudarat (Quran 4:43, 5:6).",
  },
  {
    level: 10, category: "Fiqh",
    questionText: "What is the Iddah (waiting period) for a widow whose husband has died?",
    options: ["3 months", "4 months and 10 days", "1 year", "40 days"], correctIndex: 1,
    explanation: "The widow's iddah is four lunar months and ten days (Quran 2:234), unless she is pregnant — then until delivery.",
    questionTextId: "Berapakah masa Iddah untuk seorang janda yang suaminya telah wafat?",
    optionsId: ["3 bulan", "4 bulan 10 hari", "1 tahun", "40 hari"],
    explanationId: "Iddah janda adalah empat bulan lunar dan sepuluh hari (Quran 2:234), kecuali jika hamil — maka sampai melahirkan.",
    questionTextMs: "Berapakah tempoh Iddah untuk seorang janda yang suaminya telah meninggal?",
    optionsMs: ["3 bulan", "4 bulan 10 hari", "1 tahun", "40 hari"],
    explanationMs: "Iddah janda adalah empat bulan lunar dan sepuluh hari (Quran 2:234), kecuali jika hamil — maka sehingga melahirkan.",
  },
  {
    level: 10, category: "Fiqh",
    questionText: "Which is a condition for the validity of a Muslim marriage (nikah)?",
    options: ["A wedding feast", "Mutual consent, witnesses, and mahr", "A specific dress code", "Public photography"], correctIndex: 1,
    explanation: "Validity requires the consent of both parties, two witnesses, a wali for the bride (in most schools), and the mahr.",
    questionTextId: "Mana yang merupakan syarat sahnya pernikahan Muslim (nikah)?",
    optionsId: ["Pesta pernikahan", "Persetujuan bersama, saksi, dan mahar", "Kode pakaian tertentu", "Foto publik"],
    explanationId: "Keabsahan memerlukan persetujuan kedua belah pihak, dua saksi, wali untuk pengantin wanita (di kebanyakan mazhab), dan mahar.",
    questionTextMs: "Manakah syarat kesahan perkahwinan Muslim (nikah)?",
    optionsMs: ["Majlis walimah", "Persetujuan bersama, saksi, dan mahar", "Kod pakaian tertentu", "Fotografi awam"],
    explanationMs: "Kesahan memerlukan persetujuan kedua-dua pihak, dua saksi, wali bagi pengantin perempuan (dalam kebanyakan mazhab), dan mahar.",
  },
  {
    level: 10, category: "Akhlaq",
    questionText: "What does \"Ghibah\" (backbiting) mean?",
    options: ["Praising someone in their presence", "Mentioning something about your brother that he would dislike, even if true", "Lying about someone", "Public correction"], correctIndex: 1,
    explanation: "The Prophet ﷺ defined ghibah as mentioning your brother with what he dislikes; if false, it is buhtan — slander (Muslim).",
    questionTextId: "Apa arti \"Ghibah\" (gunjing)?",
    optionsId: ["Memuji seseorang di hadapannya", "Menyebutkan sesuatu tentang saudaramu yang tidak disukainya, meskipun benar", "Berbohong tentang seseorang", "Koreksi publik"],
    explanationId: "Nabi ﷺ mendefinisikan ghibah sebagai menyebutkan saudaramu dengan apa yang tidak disukainya; jika salah, itu adalah buhtan — fitnah (Muslim).",
    questionTextMs: "Apakah maksud \"Ghibah\" (mengumpat)?",
    optionsMs: ["Memuji seseorang di hadapannya", "Menyebut sesuatu tentang saudara kamu yang tidak disukainya, walaupun benar", "Berbohong tentang seseorang", "Teguran awam"],
    explanationMs: "Nabi ﷺ mendefinisikan ghibah sebagai menyebut saudara kamu dengan apa yang tidak disukainya; jika salah, itu adalah buhtan — fitnah (Muslim).",
  },
  {
    level: 10, category: "Akhlaq",
    questionText: "Which act did the Prophet ﷺ describe as \"half of faith\"?",
    options: ["Honesty", "Patience", "Cleanliness/Purification (At-Tahur)", "Fasting"], correctIndex: 2,
    explanation: "The Prophet ﷺ said \"At-Tahuru shatrul iman\" — purification is half of faith (Muslim).",
    questionTextId: "Perbuatan apa yang disebut Nabi ﷺ sebagai \"setengah dari iman\"?",
    optionsId: ["Kejujuran", "Kesabaran", "Kebersihan/Bersuci (At-Tahur)", "Berpuasa"],
    explanationId: "Nabi ﷺ bersabda \"At-Tahuru shatrul iman\" — bersuci adalah setengah dari iman (Muslim).",
    questionTextMs: "Perbuatan apakah yang disebut oleh Nabi ﷺ sebagai \"separuh iman\"?",
    optionsMs: ["Kejujuran", "Kesabaran", "Kebersihan/Bersuci (At-Tahur)", "Berpuasa"],
    explanationMs: "Nabi ﷺ bersabda \"At-Tahuru shatrul iman\" — bersuci adalah separuh daripada iman (Muslim).",
  },
  {
    level: 10, category: "Fiqh",
    questionText: "Riba (usury / interest) is:",
    options: ["Permissible in small amounts", "Strictly forbidden in Islam", "Allowed for trade only", "Allowed if mutually agreed"], correctIndex: 1,
    explanation: "Allah declared war on those who deal in riba (Quran 2:278–279); it is among the major sins.",
    questionTextId: "Riba (riba/bunga) adalah:",
    optionsId: ["Dibolehkan dalam jumlah kecil", "Diharamkan secara ketat dalam Islam", "Dibolehkan hanya untuk perdagangan", "Dibolehkan jika disepakati bersama"],
    explanationId: "Allah menyatakan perang kepada mereka yang terlibat dalam riba (Quran 2:278–279); ia termasuk di antara dosa-dosa besar.",
    questionTextMs: "Riba (riba/faedah) adalah:",
    optionsMs: ["Dibenarkan dalam jumlah kecil", "Diharamkan secara tegas dalam Islam", "Dibenarkan untuk perdagangan sahaja", "Dibenarkan jika dipersetujui bersama"],
    explanationMs: "Allah mengisytiharkan perang kepada mereka yang terlibat dalam riba (Quran 2:278–279); ia termasuk dalam dosa-dosa besar.",
  },
  {
    level: 10, category: "Akhlaq",
    questionText: "The Prophet ﷺ said the best among you are those who are best to:",
    options: ["Their tribe", "Their families", "Strangers", "The wealthy"], correctIndex: 1,
    explanation: "\"The best of you is the one who is best to his family, and I am the best of you to my family\" (Tirmidhi).",
    questionTextId: "Nabi ﷺ bersabda bahwa yang terbaik di antara kalian adalah mereka yang paling baik kepada:",
    optionsId: ["Suku mereka", "Keluarga mereka", "Orang asing", "Orang kaya"],
    explanationId: "\"Yang terbaik di antara kalian adalah yang paling baik kepada keluarganya, dan aku adalah yang terbaik di antara kalian kepada keluargaku\" (Tirmidzi).",
    questionTextMs: "Nabi ﷺ bersabda bahawa yang terbaik di antara kamu ialah mereka yang paling baik kepada:",
    optionsMs: ["Puak mereka", "Keluarga mereka", "Orang asing", "Orang kaya"],
    explanationMs: "\"Yang terbaik di antara kamu ialah yang paling baik kepada keluarganya, dan aku adalah yang terbaik di antara kamu kepada keluargaku\" (Tirmidhi).",
  },
];

export async function seedQuizQuestions(): Promise<void> {
  // Per-level idempotency: insert questions only for levels that currently
  // have zero rows. This preserves any previously seeded questions verbatim
  // (so existing user answer history stays meaningful) while still letting
  // us add brand-new levels by simply appending entries to SEED_QUESTIONS.
  const existingLevelsResult = await db.execute<{ level: number }>(
    sql`SELECT DISTINCT level FROM ${quizQuestions}`,
  );
  const existingLevels = new Set(
    ((existingLevelsResult.rows ?? existingLevelsResult) as Array<{ level: number }>).map(
      (r) => Number(r.level),
    ),
  );

  const toInsert = SEED_QUESTIONS.filter((q) => !existingLevels.has(q.level));
  if (toInsert.length > 0) {
    await db.insert(quizQuestions).values(toInsert).onConflictDoNothing();
    const levelsAdded = Array.from(new Set(toInsert.map((q) => q.level))).sort((a, b) => a - b);
    console.log(
      `[quiz-seed] inserted ${toInsert.length} quiz questions for level(s): ${levelsAdded.join(", ")}`,
    );
  }

  // Upsert translations for all seed questions that carry id/ms variants.
  // Match by (level, question_text) to find existing rows safely — question
  // IDs already referenced by quiz_attempts.questionIds are not touched.
  let translationsUpdated = 0;
  for (const q of SEED_QUESTIONS) {
    if (!q.questionTextId && !q.questionTextMs) continue;
    const updateSet: Record<string, unknown> = {};
    if (q.questionTextId !== undefined) updateSet.questionTextId = q.questionTextId;
    if (q.optionsId !== undefined) updateSet.optionsId = q.optionsId;
    if (q.explanationId !== undefined) updateSet.explanationId = q.explanationId;
    if (q.questionTextMs !== undefined) updateSet.questionTextMs = q.questionTextMs;
    if (q.optionsMs !== undefined) updateSet.optionsMs = q.optionsMs;
    if (q.explanationMs !== undefined) updateSet.explanationMs = q.explanationMs;

    const result = await db
      .update(quizQuestions)
      .set(updateSet)
      .where(
        and(
          eq(quizQuestions.level, q.level),
          eq(quizQuestions.questionText, q.questionText),
        ),
      );
    if (result.rowCount && result.rowCount > 0) translationsUpdated++;
  }
  if (translationsUpdated > 0) {
    console.log(`[quiz-seed] upserted translations for ${translationsUpdated} question(s).`);
  }
}
